src/python/library/tritonclient/http/__init__.py

See this for reference: https://github.com/triton-inference-server/server/issues/2725

Fix ssl related documentation in python httpclient

---

src/c++/perf_analyzer/inference_profiler.cc
src/c++/perf_analyzer/inference_profiler.h
src/c++/perf_analyzer/load_manager.cc
src/c++/perf_analyzer/load_manager.h
src/c++/perf_analyzer/main.cc

The count based algorithm can be enabled by using the `--window-size` flag. I didn't reuse the `-p` flag because it still would require another flag to interpret the meaning of `-p` flag.

Add count-based stabilization

---

src/c++/perf_analyzer/inference_profiler.cc
src/c++/perf_analyzer/main.cc

Sample of the new message log:
```
*** Measurement Settings ***
Batch size: 1
Using "count_windows" mode for stabilization
Minimum number of samples in each window: 50
Using synchronous calls for inference
Stabilizing using average latency
```

Improve the logging for the count_windows mode

---

src/c++/perf_analyzer/load_manager.cc

We need to add some very specific tests for perf_analyzer for all these small cases.
Need to revisit L0_perf_analyzer and modularize it.

Fix the sequence flags in case of single request per sequence

---

src/java/pom.xml

Built the java client with this fix locally, and vulnerabilities packages no longer exists.

Fix java vulnerabilities for L1_contamer

---

README.md
src/python/library/setup.py

The project page will look like:
https://test.pypi.org/project/tritonclient/
I have already uploaded the earlier wheels on the pyPI but currently it lacks the project description,
https://pypi.org/project/tritonclient/
@aramesh7 Similar changes will be needed for the triton-model-analyzer wheels as well..

Updates documentation for tritonclient wheels to be published on pyPI

---

src/python/library/tritonclient/grpc/__init__.py

This PR adds support for user provided grpc.ChannelCredentials to the python client library.

[python] add support for user provided ChannelCredentials

---

src/c++/perf_analyzer/inference_profiler.cc

This fixes infinite hang when there is an error in requests returned in count_windows mode.

Fix error handling in count_windows mode

---

README.md

Underscores have to be escaped with `\` to avoid bold formatting.
Preview: https://github.com/theHamsta/client/tree/fix-readme-formatting

docs: fix rendering of `__init__` in README

---

README.md
src/c++/examples/simple_http_infer_client.cc
src/c++/library/http_client.cc
src/c++/library/http_client.h
src/python/examples/simple_http_infer_client.py

I have exposed decent SSL curl options in our HTTP  C++ client library to bring it upto the parity with python client and grpc library.
There are many other settings that can be exposed like loading a key from crypto engine etc. which most likely goes beyond the scope of the requirement. 
@matthewkotila  Look at the options exposed in `simple_http_infer_client.cc`. Something very similar needs to be done for the perf_analyzer to work with SSL settings.  
Tests are added here: https://github.com/triton-inference-server/server/pull/3862

Expose SSL options in HTTP C++ library and client examples

---

src/c++/library/http_client.cc

Currently, the [static CurlGlobal curl_global](https://github.com/triton-inference-server/client/blob/27522b01698b71b3fdb7ebe90ffe88e962b82789/src/c%2B%2B/library/http_client.cc#L86) instance expects to be constructed after Error::Success, since the [CurlGlobal constructor](https://github.com/triton-inference-server/client/blob/27522b01698b71b3fdb7ebe90ffe88e962b82789/src/c%2B%2B/library/http_client.cc#L74) references [Error::Success](https://github.com/triton-inference-server/client/blob/27522b01698b71b3fdb7ebe90ffe88e962b82789/src/c%2B%2B/library/common.cc#L33).
This leads to a race condition in Centos7, as the two global objects sit in separate translation units, http_client.cc and common.cc. This PR merges a fix to make the CurlGlobal object a singleton, so it is always initialized …

Remove CurlGlobal Race Condition

---

src/c++/perf_analyzer/concurrency_manager.cc

Fix async PA with binary search in concurrency mode. 
Server side test: https://github.com/triton-inference-server/server/pull/3982
Same as https://github.com/triton-inference-server/client/pull/66.

Fix Async PA with binary search 

---

src/python/library/tritonclient/http/__init__.py
src/python/library/tritonclient/utils/shared_memory/__init__.py

[Bug] Exception was raised when using offset !=0 in set_shared _memory of InferInput of Http client
https://github.com/triton-inference-server/server/issues/3986
[Feature] support offset for get_contents_as_numpy and set_shared_memory_region of shm lib
https://github.com/triton-inference-server/server/issues/3987

Support non-zero shm offset in tritonclient.utils.shared_memory

---

src/python/examples/simple_grpc_shm_client.py
src/python/examples/simple_http_shm_client.py

- Leverage new offset param in shared memory utils
Testing/sample to accompany https://github.com/triton-inference-server/client/pull/74 (Rebased after merge)

Update python simple examples to use single shared memory region for input and output

---

src/c++/examples/simple_grpc_infer_client.cc
src/c++/library/grpc_client.cc
src/c++/library/grpc_client.h

Add `use_cached_channel` variable to force create a new channel if set to false
instead of using the old channel for grpc client
Server test PR: https://github.com/triton-inference-server/server/pull/4325

Add option to force create new channel

---

src/c++/examples/CMakeLists.txt
src/c++/examples/simple_grpc_custom_args_client.cc
src/c++/library/grpc_client.cc
src/c++/library/grpc_client.h
src/python/examples/CMakeLists.txt
src/python/examples/simple_grpc_custom_args_client.py
src/python/library/tritonclient/grpc/__init__.py

* Add custom ChannelArguments parameter to grpc C++ client library for generic user-defined settings
* Add placeholder C++ example, followup on TODOs
* Add overloaded methods to accept grpc::ChannelArguments instead of KeepAliveOptions. Update cpp example to use new ChannelArguments for KeepAlive settings instead
* rename to channel_args, clang-format
* Expose channel_args option to python client for custom user-defined GRPC ChannelArguments
* Add python example of setting custom grpc channel arguments
* Add cached_channel param from merge conflict
* Add example channel argument requested for this feature
* update copyright
* Fix test name output typo
* Cleanup dupe constructors and GetStub per review comments
* Add new python example clients to install directory
* copyright
* remove …

Expose custom GRPC ChannelArguments in client libraries (#104)

---

src/c++/perf_analyzer/inference_profiler.cc
src/c++/perf_analyzer/inference_profiler.h
src/c++/perf_analyzer/perf_analyzer.cc

Aggregate trial statistics to report the average of trials instead of reporting the last trial.
```
*** Measurement Settings ***
Batch size: 1
Using "time_windows" mode for stabilization
Measurement window: 5000 msec
Using synchronous calls for inference
Stabilizing using average latency
Request concurrency: 1
Pass [1] throughput: 269.4 infer/sec. Avg latency: 3705 usec (std 220 usec)
Pass [2] throughput: 267.4 infer/sec. Avg latency: 3733 usec (std 239 usec)
Pass [3] throughput: 268.6 infer/sec. Avg latency: 3714 usec (std 228 usec)
Client:
Request count: 4027
Throughput: 268.467 infer/sec
Avg latency: 3717 usec (standard deviation 229 usec)
p50 latency: 3736 usec
p90 latency: 3983 usec
p95 latency: 4010 usec
p99 latency: 4049 usec
Avg HTTP time: 3699 usec (send 148 usec + response wait …
```

Aggregate trial statistics

---

.gitignore
src/c++/perf_analyzer/inference_profiler.cc
src/c++/perf_analyzer/inference_profiler.h
src/c++/perf_analyzer/perf_analyzer.cc

Refactor stability checking code.  
Update stability check to use a new formula: max/min < 1 + stability_threshold  
Adds unit testing for the stability numbers

update stability formula

---

src/c++/perf_analyzer/inference_profiler.cc

Before:
```
root@itabrizian-dt:/opt/tritonserver/qa/L0_perf_nomodel# perf_analyzer -m identity_fp32 --shape INPUT0:1 -r 1
*** Measurement Settings ***
Batch size: 1
Using "time_windows" mode for stabilization
Measurement window: 5000 msec
Using synchronous calls for inference
Stabilizing using average latency
Request concurrency: 1
Perf Status reports size must match the stability window.
```
After:
```
*** Measurement Settings ***
Batch size: 1
Using "time_windows" mode for stabilization
Measurement window: 5000 msec
Using synchronous calls for inference
Stabilizing using average latency
Request concurrency: 1
Failed to obtain stable measurement within 1 measurement windows for concurrency 1. Please try to increase the --measurement-interval.
```

Only merge the results if they are stable

---

src/python/examples/grpc_image_client.py

Fix grpc_image_client.py to support models with/without batching, and make sure it works with the `densenet_onnx` example that does not have batching (vs `inception_graphdef`).
The PR extends fixes from https://github.com/triton-inference-server/client/pull/103/files

Add non-batching model support to grpc_image_client.py

---

src/c++/perf_analyzer/inference_profiler.cc
src/c++/perf_analyzer/inference_profiler.h

After:
```
/opt/tritonserver/bin/perf_analyzer -m identity_fp32 --shape INPUT0:1 -t 32 -f my_file.csv
*** Measurement Settings ***
Batch size: 1
Using "time_windows" mode for stabilization
Measurement window: 5000 msec
Using synchronous calls for inference
Stabilizing using average latency
Request concurrency: 32
Client:
Request count: 30
Throughput: 1.66619 infer/sec
Avg latency: 17695686 usec (standard deviation 0 usec)
p50 latency: 19260511 usec
p90 latency: 19261207 usec
p95 latency: 19261332 usec
p99 latency: 19261533 usec
Avg HTTP time: 17695644 usec (send/recv 2037 usec + response wait 17693607 usec)
Server:
Inference count: 30
Execution count: 30
Successful request count: 30
Avg request latency: 17691933 usec (overhead 99 usec + queue 17090118 usec + compute input 134 usec + …
```

Improve server side and client side metrics collection

---

src/c++/CMakeLists.txt

Currently, googletest is always fetched when building the client, leading to gtest and gmock includes and libraries being installed. However, this dependency is only needed for the examples and the perf client, so it should only be fetched when those are enabled.

only fetch googletest when needed

---

src/c++/perf_analyzer/client_backend/triton_c_api/triton_loader.cc
src/c++/perf_analyzer/client_backend/triton_c_api/triton_loader.h

Clean up and refactor some clean up code when the c_api experiences errors.
Attach the error_message_fn pointer to avoid segfaults

 c api segfault fixes

---

src/c++/perf_analyzer/perf_analyzer.cc

Stop overwriting bubbled up error with a generic error.

Fix overwriting unstable error code

---

src/python/library/build_wheel.py

The `sys` module is used in `fail_if` (please see below). However it was not imported. So this adds that `import` to fix the missing import issue.
https://github.com/triton-inference-server/client/blob/f560cb3b928f86f167cf6d0b764c46c50226f8b8/src/python/library/build_wheel.py#L39-L42

Add missing `import sys`

---

src/c++/perf_analyzer/inference_profiler.cc

Updating grpc timing calculations.  
Time accumulation was being done twice on new configurations. Resetting the calculation when window_start_ns == 0 removes the duplication.

Fix grpc timing calculations

---

src/java-api-bindings/scripts/install_dependencies_and_build.sh

Originally the long options of `--jar-install-path`, `--javacpp-branch-tag` flags did not work. Also help exits properly now

Fix java api bindings install script

---

src/c++/perf_analyzer/inference_profiler.cc
src/c++/perf_analyzer/inference_profiler.h
src/c++/perf_analyzer/perf_analyzer.cc

I have manually tested the following things:
* Test that GPU code does/doesn't get called when `--collect-metrics` option is true/false
* Test that user-set value for `--metrics-url` option gets used for triton metrics curl
* Test that default value for `--metrics-url` is used when option is unspecified
* Test that error is thrown when using `--metrics-url` without `--collect-metrics`
* Test that value for `--metrics-interval` option gets passed to thread sleep/callback logic for curling triton metrics
* Test that default value for `--metrics-interval` option is used when option is unspecified
* Test that error is thrown when using `--metrics-interval` without `--collect-metrics`
* Test that error is thrown when 0 is specified for `--metrics-interval`
I will add testing in a future PR for …

Implement various CLI options

---

src/c++/perf_analyzer/CMakeLists.txt
src/c++/perf_analyzer/client_backend/client_backend.cc
src/c++/perf_analyzer/client_backend/client_backend.h
src/c++/perf_analyzer/client_backend/triton/CMakeLists.txt
src/c++/perf_analyzer/client_backend/triton/test_triton_client_backend.cc
src/c++/perf_analyzer/client_backend/triton/triton_client_backend.cc
src/c++/perf_analyzer/client_backend/triton/triton_client_backend.h
src/c++/perf_analyzer/command_line_parser.cc
src/c++/perf_analyzer/command_line_parser.h
src/c++/perf_analyzer/inference_profiler.cc
src/c++/perf_analyzer/inference_profiler.h
src/c++/perf_analyzer/metrics.h
src/c++/perf_analyzer/metrics_manager.cc
src/c++/perf_analyzer/metrics_manager.h
src/c++/perf_analyzer/perf_analyzer.cc
src/c++/perf_analyzer/report_writer.cc
src/c++/perf_analyzer/report_writer.h
src/c++/perf_analyzer/test_inference_profiler.cc
src/c++/perf_analyzer/test_metrics_manager.cc
src/c++/perf_analyzer/test_report_writer.cc

* Implement triton metric collection (#154)
* Implement triton metric collection
* Addressed comments
* Addressed comments
* Fix bugs
* Addressed comments
* Addressed comments
* Addressed comments
* Implement GPU metrics aggregation (#158)
* Implement GPU metrics aggregation
* Addressed comments
* Implement various CLI options (#160)
* Implement various CLI options
* Addressed comments
* Implement gpu total memory metric collection and aggregation (#161)
* Implement gpu total memory metric collection and aggregation
* Remove unnecessary logic
* Fix warning bug
* Add gpu metrics csv output (#162)
* Update options to use defines
* Update metric option to collect-gpu-metrics and plumb option to report writer
* Add new headers for gpu metrics
* Add assert to ensure vector is size 1
* Guard …

Gpu metrics support (#164)

---

src/c++/perf_analyzer/client_backend/client_backend.h
src/c++/perf_analyzer/concurrency_manager.cc
src/c++/perf_analyzer/concurrency_manager.h
src/c++/perf_analyzer/custom_load_manager.cc
src/c++/perf_analyzer/custom_load_manager.h
src/c++/perf_analyzer/load_manager.cc
src/c++/perf_analyzer/load_manager.h
src/c++/perf_analyzer/request_rate_manager.cc
src/c++/perf_analyzer/request_rate_manager.h

Move all logic out of Create functions into constructors
Move common code of InitManagerInputs() and InitSharedMemory() into base class
threads_config_.reserve(max_threads) has to stay in child classes because they don't share thread_config type

Move logic from load manager create functions into constructors

---

src/c++/library/common.h
src/c++/library/http_client.cc
src/c++/library/http_client.h

Using `curl_multi_wait` instead of busyloop to wait for server responses. This decreases client CPU usage.

Add timeout to avoid busyloop in async http client

---

src/python/library/requirements/requirements_http.txt

Looks like geventhttpclient has changed handling of ssl_context_factory in 2.0.8 release that is making our L0_https fail.
Need to take a deeper look into what needs to change to move to 2.0.8 versions and later.

Restrict the geventhttpclient version to 2.0.2

---

src/c++/perf_analyzer/client_backend/mock_client_backend.h
src/c++/perf_analyzer/mock_model_parser.h
src/c++/perf_analyzer/model_parser.h
src/c++/perf_analyzer/test_concurrency_manager.cc
src/c++/perf_analyzer/test_inference_profiler.cc
src/c++/perf_analyzer/test_load_manager.cc
src/c++/perf_analyzer/test_load_manager_base.h
src/c++/perf_analyzer/test_request_rate_manager.cc

There's only two places in RequestRateManager, currently, that do custom logic when in streaming mode:
1. https://github.com/triton-inference-server/client/blob/f74b6232a5fe9a85ea24a9dd3185f30a0d51cbe9/src/c++/perf_analyzer/request_rate_manager.cc#L237-L244
*  This is the new verification added in this PR. I check that StartStream() gets called by recording the enable_stats parameter.
2. https://github.com/triton-inference-server/client/blob/f74b6232a5fe9a85ea24a9dd3185f30a0d51cbe9/src/c++/perf_analyzer/request_rate_manager.cc#L389-L392
* This is already verified in [CheckInferType()](https://github.com/triton-inference-server/client/blob/main/src/c%2B%2B/perf_analyzer/test_load_manager_base.h#L55)/[request_rate_infer_type](https://github.com/triton-inference-server/client/blob/main/src/c% …

Test streaming in RequestRateManager

---

src/c++/library/CMakeLists.txt

PRIVATE should not have extra ":". In this state, cmake consider than PRIVATE: is a library and not the keyword PRIVATE which leads to failure.
cmake version 3.22.2
GNU Make 4.1
Built for x86_64-pc-linux-gnu

remove extra colons from cmake in library/c++

---

src/c++/library/http_client.cc

This PR removes std:move call to fix the -Werror,-Wpessimizing-move issue. Thanks for the review.
```
In file included from /../cmake-build/external/triton/client/src/c++/library/CMakeFiles/http-client-library.dir/Unity/unity_0_cxx.cxx:3:
/../external/triton/client/src/c++/library/http_client.cc:1257:31: error: moving a temporary object prevents copy elision [-Werror,-Wpessimizing-move]
pr.first.c_str(), std::move(triton::common::TritonJson::Value()));
^
/../external/triton/client/src/c++/library/http_client.cc:1257:31: note: remove std::move call here
pr.first.c_str(), std::move(triton::common::TritonJson::Value()));
```
cmake version 3.22.2
GNU Make 4.1
Built for x86_64-pc-linux-gnu

remove std::move call

---

src/c++/perf_analyzer/client_backend/mock_client_backend.h
src/c++/perf_analyzer/concurrency_manager.cc
src/c++/perf_analyzer/concurrency_manager.h
src/c++/perf_analyzer/load_manager.h
src/c++/perf_analyzer/request_rate_manager.cc
src/c++/perf_analyzer/test_concurrency_manager.cc
src/c++/perf_analyzer/test_load_manager_base.h
src/c++/perf_analyzer/test_request_rate_manager.cc

The following image shows how the load managers used to behave, and how they will behave now:
Changes:
- ConcurrencyManager:
- Refactor ChangeConcurrencyLevel into 3 functions
- Update the pause/resume code to happen for all sequences, not just async sequences
- Finish all sequences immediately instead of executing the full length
- Finish all sequences instead of just async
- RequestRateManager:
- Finish all sequences (immediately) between rates
- Because any thread can issue to any sequence, I needed a way to communicate between threads to make sure one thread didn't "finish" a sequence only to have another thread restart it. 
- This resulted in adding a pause variable into SequenceStat
- Testing:
- Move all param creation code for testing sequences into test_load_manager_base so it can …

Standardize handling of sequences by LoadManagers

---

src/c++/perf_analyzer/client_backend/mock_client_backend.h
src/c++/perf_analyzer/concurrency_manager.cc
src/c++/perf_analyzer/inference_profiler.cc
src/c++/perf_analyzer/test_concurrency_manager.cc
src/c++/perf_analyzer/test_request_rate_manager.cc

- Fixed a bug where timestamps after the last window of the previous rate were incorrectly carried over to the next rate
- Added a check to confirm that after Pausing workers, the clients and the manager are in sync with their stats. This exposed a bug in ConcurrencyManager (and confirmed correct behavior in RequestRateManager)
- Fixed the bug mentioned above in ConcurrencyManager

Fix bugs where stats carried forward between rates

---

src/python/library/requirements/requirements_grpc.txt

Update to 1.42.0 to still avoid the memory leak but updated enough to allow using python 3.10 +
https://github.com/triton-inference-server/client/pull/92#issuecomment-1296376735

Update grpcio versions

---

src/c++/perf_analyzer/inference_profiler.cc

The code was incorrectly clearing out the server stats. What was supposed to happen (and already was immediately above it) was to synchronize the server stats at the start of the first window.

Fix bug where first window had no starting server stats

---

src/c++/perf_analyzer/load_manager.cc
src/c++/perf_analyzer/test_load_manager.cc

Any existing value in the object should be ignored. The result of the function should only factor in the data in the contexts and nothing else

Fix bug in GetAccumulatedClientStat

---

src/c++/library/common.h
src/c++/library/http_client.cc
src/c++/perf_analyzer/doctest.h
src/c++/perf_analyzer/test_perf_utils.cc
src/c++/perf_analyzer/test_utils.h
src/python/examples/simple_http_aio_infer_client.py
src/python/library/tritonclient/grpc/__init__.py
src/python/library/tritonclient/http/__init__.py
src/python/library/tritonclient/utils/__init__.py

Clarify `server_timeout` usage in documentation
Related server PR: https://github.com/triton-inference-server/server/pull/5169
Formatted:
```
modified:   src/c++/library/http_client.cc
modified:   src/c++/perf_analyzer/doctest.h
modified:   src/c++/perf_analyzer/test_perf_utils.cc
modified:   src/c++/perf_analyzer/test_utils.h
modified:   src/python/examples/simple_http_aio_infer_client.py
modified:   src/python/library/tritonclient/utils/__init__.py
```

Clarify timeout documentation and added formatting

---

src/python/library/requirements/requirements_grpc.txt

ONNX package is installed to test ONNX flavor logic in L0_mlflow, which replies on newer proto3 library. Before the change, installing Triton client will downgrade the proto3 library and break ONNX dependency

Relax protobuf range to fix L0_mlflow

---

src/c++/perf_analyzer/data_loader.cc

File was being closed too early. RapidJson documentation shows closing file after call to `ParseStream()`:
https://rapidjson.org/md_doc_stream.html#FileReadStream

Fix input json reading bug

---

src/c++/perf_analyzer/client_backend/mock_client_backend.h
src/c++/perf_analyzer/concurrency_manager.h
src/c++/perf_analyzer/concurrency_worker.cc
src/c++/perf_analyzer/test_concurrency_manager.cc
src/c++/perf_analyzer/test_request_rate_manager.cc

CTX IDs were being incorrectly reset over and over instead of just when the contexts are created during setup.
Added a test to expose the issue, which involved adding the ability to specify multiple response latencies instead of just one fixed one.

Fix CTX IDs bug for concurrency manager

---

src/java/src/main/java/triton/client/InferenceServerClient.java

If there is no path, `null` is included in the url and the post request is sent.
`/null/v2/models/<model_name>/infer`
So, defense logic is added so that only `requestUri` is added in case of null.
---
Environment: spring boot + kotlin
Used by importing `jar`

[Java] Fix the phenomenon that null is set in path

---

src/c++/perf_analyzer/client_backend/triton_c_api/triton_loader.cc

Capturing by the reference in lambda function to properly clear out the response object.

Fix the infer_response clean-up logic in perf_analyzer C-API

---

src/c++/perf_analyzer/concurrency_manager.cc
src/c++/perf_analyzer/concurrency_worker.cc
src/c++/perf_analyzer/concurrency_worker.h
src/c++/perf_analyzer/load_worker.cc
src/c++/perf_analyzer/load_worker.h
src/c++/perf_analyzer/request_rate_manager.cc
src/c++/perf_analyzer/request_rate_worker.cc
src/c++/perf_analyzer/request_rate_worker.h
src/c++/perf_analyzer/test_concurrency_manager.cc
src/c++/perf_analyzer/test_request_rate_manager.cc

The main thing this does is makes it so that UpdateJsonData doesn't have to be implemented in child classes. That way it is self-contained in the load worker base class.
Also:
- removed DataStepIdTracker from ThreadConfig so it is common
- Gave load_worker an ID (which I think we will need for other reasons later)

Make json code self-contained in load_worker

---

src/c++/perf_analyzer/concurrency_worker.cc
src/c++/perf_analyzer/load_worker.cc
src/c++/perf_analyzer/request_rate_worker.h

old code had potential race conditions around free_ctx_ids and total_ongoing_requests, which prevented me from putting total_ongoing_requests in a common location. This fixes that. It also fixes a bug where in some cases free_ctx_ids was being pushed and not popped.

Fix free_ctx_id tracking, and decouple total_ongoing_request tracking

---

src/c++/perf_analyzer/concurrency_worker.cc
src/c++/perf_analyzer/concurrency_worker.h
src/c++/perf_analyzer/infer_context.h

SyncClientStats is no longer needed. It was added to fix a bug (https://github.com/triton-inference-server/client/pull/195). As [this](https://github.com/triton-inference-server/client/pull/195/files#r1026567361) comment mentions, there were two ways to fix it. We have since also implemented the 2nd fix, which means that this first fix is no longer needed.
I confirmed that a unit test was added in 195 that would catch this error if it was reintroduced.

Remove SyncClientStats()

---

src/c++/perf_analyzer/client_backend/mock_client_backend.h
src/c++/perf_analyzer/concurrency_worker.cc
src/c++/perf_analyzer/infer_context.cc
src/c++/perf_analyzer/load_worker.cc
src/c++/perf_analyzer/load_worker.h
src/c++/perf_analyzer/request_rate_worker.cc
src/c++/perf_analyzer/test_concurrency_manager.cc
src/c++/perf_analyzer/test_request_rate_manager.cc
src/c++/perf_analyzer/test_utils.h

Standardized exit condition detection for the workers
Created ability to control when the mock backend returns failure instead of success
Created a Watchdog to detect livelock/deadlock in tests
Created tests to try to stress timing to try to find deadlocks
Note: This adds 90 seconds to our unit test runtime. We may decide to pull some of this back or shorten it.

Add deadlock/livelock testing

---

src/c++/perf_analyzer/custom_load_manager.cc
src/c++/perf_analyzer/custom_load_manager.h
src/c++/perf_analyzer/perf_analyzer.cc
src/c++/perf_analyzer/request_rate_manager.cc
src/c++/perf_analyzer/request_rate_manager.h
src/c++/perf_analyzer/request_rate_worker.cc
src/c++/perf_analyzer/request_rate_worker.h
src/c++/perf_analyzer/test_custom_load_manager.cc
src/c++/perf_analyzer/test_load_manager_base.h
src/c++/perf_analyzer/test_request_rate_manager.cc

There were some corner case bugs at the boundaries of the request_rate and custom_load schedules. 
The request_rate bug was minor, but having an odd request_rate that couldn't perfectly divide the window would have a minor hiccup when wrapping
The custom_load bug was more significant -- when wrapping around the schedule we could actually go back in time.
This PR adds unit tests to expose them, and then fixes the issue by creating a full schedule instead of a partial schedule that has to be looped.

Test and fix request schedules

---

src/c++/perf_analyzer/CMakeLists.txt
src/c++/perf_analyzer/concurrency_manager.cc
src/c++/perf_analyzer/concurrency_manager.h
src/c++/perf_analyzer/concurrency_worker.h
src/c++/perf_analyzer/custom_load_manager.cc
src/c++/perf_analyzer/custom_load_manager.h
src/c++/perf_analyzer/data_loader.h
src/c++/perf_analyzer/infer_context.cc
src/c++/perf_analyzer/infer_context.h
src/c++/perf_analyzer/load_manager.cc
src/c++/perf_analyzer/load_manager.h
src/c++/perf_analyzer/load_worker.h
src/c++/perf_analyzer/perf_analyzer.cc
src/c++/perf_analyzer/request_rate_manager.cc
src/c++/perf_analyzer/request_rate_manager.h
src/c++/perf_analyzer/request_rate_worker.cc
src/c++/perf_analyzer/request_rate_worker.h
src/c++/perf_analyzer/sequence_manager.cc
src/c++/perf_analyzer/sequence_manager.h
src/c++/perf_analyzer/sequence_status.h
src/c++/perf_analyzer/test_concurrency_manager.cc
src/c++/perf_analyzer/test_custom_load_manager.cc
src/c++/perf_analyzer/test_load_manager.cc
src/c++/perf_analyzer/test_load_manager_base.h
src/c++/perf_analyzer/test_request_rate_manager.cc
src/c++/perf_analyzer/test_sequence_manager.cc

* Pulls some sequence code out from InferContext and moves it into its own SequenceManager class.
* Adds SequenceManager testing
* Removes concept of SequenceStat.paused
* Removes disseminating of sequence length, start sequence id, and sequence id range from a lot of classes (now only kept in SequenceManager)

Add sequence manager

---

src/c++/perf_analyzer/command_line_parser.cc

Accidentally set `--shared-memory host` instead of `--shared-memory system` and noticed no error was raised, so it silently didn't use shared memory. This should fix that.

Add check for invalid --shared-memory arg

---

README.md
src/c++/perf_analyzer/README.md

This is a copy-and-paste from the server repo.
Related PR is https://github.com/triton-inference-server/server/pull/5380

Relocate perf analyzer docs

---

src/c++/perf_analyzer/client_backend/tensorflow_serving/tfserve_infer_input.h
src/c++/perf_analyzer/data_loader.cc

I have tested these changes locally to confirm that they remove the crashes seen by the user who reported the issue.
I do not have explicit testing in place to catch these, yet.
* The class data member not being initialized to zero is a symptom of assuming the compiler would do so. A repo-wide stylistic change to initialize all data members (and variables in general) would be an appropriate fix. Also more unit testing of the class for the data member. All stuff I would prefer to do in future, not now for a quick bug fix.
* The division by zero is also a symptom of the data loader class not having unit testing. I'd prefer to do that later in a dedicated story.

Fix various tfserve bugs

---

src/c++/perf_analyzer/CMakeLists.txt
src/c++/perf_analyzer/concurrency_worker.cc
src/c++/perf_analyzer/idle_timer.h
src/c++/perf_analyzer/infer_context.cc
src/c++/perf_analyzer/infer_context.h
src/c++/perf_analyzer/inference_profiler.cc
src/c++/perf_analyzer/inference_profiler.h
src/c++/perf_analyzer/load_manager.cc
src/c++/perf_analyzer/load_manager.h
src/c++/perf_analyzer/request_rate_worker.cc
src/c++/perf_analyzer/test_concurrency_manager.cc
src/c++/perf_analyzer/test_idle_timer.cc
src/c++/perf_analyzer/test_inference_profiler.cc
src/c++/perf_analyzer/test_load_manager.cc
src/c++/perf_analyzer/test_request_rate_manager.cc

Track overhead in perf analyzer. This is any time that PA is not calling a backend function and not sleeping/waiting until it is time to issue a new request.
new class IdleTimer with proper unit testing
add idle timing around backend function calls as well as worker wait/sleep periods
All time not idle is considered overhead
Add function in LoadManager to bubble up average worker idle time
Add function in InferenceProfiler to calculate and store per-window overhead percentage

Track overhead

---

src/c++/perf_analyzer/infer_context.cc
src/c++/perf_analyzer/infer_context.h
src/c++/perf_analyzer/inference_profiler.cc
src/c++/perf_analyzer/inference_profiler.h
src/c++/perf_analyzer/load_manager.cc
src/c++/perf_analyzer/load_manager.h
src/c++/perf_analyzer/test_concurrency_manager.cc
src/c++/perf_analyzer/test_inference_profiler.cc
src/c++/perf_analyzer/test_load_manager.cc
src/c++/perf_analyzer/test_request_rate_manager.cc

* Each thread in load manager now increments a counter when a request is sent
* These counters are summed up by the InferenceProfiler once per window to calculate send request rate
* The send request rate metric is stored in the PerfStatus object in InferenceProfiler

Add request send rate detection

---

src/c++/perf_analyzer/CMakeLists.txt
src/c++/perf_analyzer/command_line_parser.h
src/c++/perf_analyzer/inference_profiler.cc
src/c++/perf_analyzer/inference_profiler.h
src/c++/perf_analyzer/perf_analyzer.cc
src/c++/perf_analyzer/perf_analyzer.h

Something was funky on main that caused the commits from Tim. The commits are still there but my work should be clean compared to main now and should only show my changes in the diff.
Updated:
- Report the overhead percentage and the request rate (only in verbose mode)
- Warn when overhead exceeds 10%. 10% is hardcoded for now and will be adjustable in the future.
- Renamed all of the perf status variables in the code base. It was not clear what each was referencing before the name changes

report overhead and request rate

---

src/c++/perf_analyzer/report_writer.cc

Old code was missing an endline after the header, resulting in the first results being in the same row

Fix composing model csv file

---

src/c++/perf_analyzer/inference_profiler.cc

Fix perf_status initialization and only add profile measurements for stable runs

Fixing repeated results 

---

src/c++/perf_analyzer/README.md
src/c++/perf_analyzer/command_line_parser.cc
src/c++/perf_analyzer/docs/README.md
src/c++/perf_analyzer/docs/inference_load_modes.md
src/c++/perf_analyzer/docs/input_data.md
src/c++/perf_analyzer/docs/measurements_metrics.md
src/c++/perf_analyzer/docs/request_sending_modes.md

* Add request sending modes doc (concurrency/request rate/custom interval)
* Fix top-level readme links
* Add note about random data generation to input data doc
* Add note about latency overhead category to measurements doc
* Fix triton C API help message outdated options

Fix various things in docs

---

src/python/library/build_wheel.py

This is a clone of https://github.com/triton-inference-server/client/pull/263.

Enable ppc64le builds for Python wheels

---

src/python/library/requirements/requirements_http.txt

Fix: [#5666](https://github.com/triton-inference-server/server/issues/5666)

Set range of aiohttp (>=3.8.1,<4.0.0) to avoid installing error in Python 3.10

---

src/c++/perf_analyzer/load_manager.h
src/c++/perf_analyzer/request_rate_manager.cc
src/c++/perf_analyzer/request_rate_manager.h
src/c++/perf_analyzer/test_request_rate_manager.cc

Remove deadcode function ResetWorkers()
See https://github.com/triton-inference-server/client/pull/242/files#r1098294907 for when this became deadcode.

Remove deadcode ResetWorkers

---

src/c++/library/common.h
src/c++/library/http_client.cc
src/c++/tests/memory_leak_test.cc

1. Refactor memory_leak_test.cc
- Fix behavior of -R (reuse) flag to actually reuse client/connection. Previously subsequent calls to `client::Create(reuse_client.  ...)` would just create new client objects under the hood.
- Template helper functions since HTTP and GRPC APIs used are identical in this test
2. Update C++ HTTP client to correctly propogate errors on client-side curl failures. Now the behavior matches other API call failures, rather than reporting an obscure Timer and Json parsing issue. See the before/after examples below:
Before:
```
root@rmccormick-dt:/workspace# memory_leak_test
Failed to update context stat: Timer not set correctly. Send time from 1682559474332558400 to 0.
error: unable to run model: failed to parse the request JSON buffer: The document is empty. at 0 …
```

Improve L0_client_memory_growth test

---

src/c++/perf_analyzer/concurrency_worker.cc
src/c++/perf_analyzer/concurrency_worker.h
src/c++/perf_analyzer/load_worker.cc
src/c++/perf_analyzer/load_worker.h
src/c++/perf_analyzer/request_rate_worker.cc
src/c++/perf_analyzer/request_rate_worker.h
src/c++/perf_analyzer/test_custom_load_manager.cc
src/c++/perf_analyzer/test_load_manager_base.h
src/c++/perf_analyzer/test_request_rate_manager.cc

Update GetCtxId for request_rate_worker to pick (approximately) round robin from all contexts instead of hardcoded to 0.
Moves the following functions up into LoadWorker to be shared:
- RestoreFreeCtxID 
- AsyncCallbackFinalize
- GetCtxId

update get ctxid

---

src/c++/perf_analyzer/inference_profiler.cc

[Here](https://github.com/triton-inference-server/client/pull/324/files#diff-1d869f26de26a6908d10260f21bd433d63ab260cd58156aed650f563001547d1R1021) we are incrementing, but the value was never initialized to 0. The result is that any random overhead could be reported depending on where that variable ended up in memory.
Technically the send_request_rate was initialized to 0 in the struct so that change wasn't as necessary, but I added an explicit reset to 0 in case the object is reused.

Fix uninitialized value bug

---

src/c++/library/common.cc
src/c++/library/common.h
src/c++/library/http_client.cc
src/c++/perf_analyzer/client_backend/client_backend.cc
src/c++/perf_analyzer/client_backend/client_backend.h
src/c++/perf_analyzer/client_backend/triton/triton_client_backend.cc
src/c++/perf_analyzer/client_backend/triton/triton_client_backend.h
src/c++/perf_analyzer/command_line_parser.cc
src/c++/perf_analyzer/command_line_parser.h
src/c++/perf_analyzer/docs/cli.md
src/c++/perf_analyzer/perf_analyzer.cc
src/c++/perf_analyzer/perf_utils.cc
src/c++/perf_analyzer/perf_utils.h

* implements ability to use json content type (in addition to binary) for inputs in inference request in c++ client
* implements ability to use json content type (in addition to binary) for outputs in inference response in c++ client
* implements two new PA options (`--json-input-data` and `--json-output-data`, which propagate down this preference to c++ client for inference requests/response input/output data formats)
* adds documentation for new PA option

Add support for json input and output content type

---

src/c++/perf_analyzer/data_loader.cc
src/c++/perf_analyzer/data_loader.h
src/c++/perf_analyzer/mock_data_loader.h
src/c++/perf_analyzer/perf_utils.cc
src/c++/perf_analyzer/perf_utils.h
src/c++/perf_analyzer/test_dataloader.cc

Add testing for DataLoader::ReadDataFromDir
This also moves ReadFile and ReadTextFile from perf_utils into the DataLoader class
Coverage up to 73% despite adding not-unit-testable file system code to the file.

Add testing for ReadDataFromDir

---

src/c++/CMakeLists.txt
src/c++/examples/simple_http_string_infer_client.cc
src/c++/library/CMakeLists.txt
src/c++/library/http_client.cc
src/c++/perf_analyzer/command_line_parser.cc
src/c++/perf_analyzer/test_command_line_parser.cc
src/c++/perf_analyzer/test_perf_utils.cc
src/c++/tests/cc_client_test.cc

* Adds testing for
* `HttpInferRequest::ConvertBinaryInputsToJSON()`
* `HttpInferRequest::ConvertBinaryInputToJSON()`
* `InferResultHttp::ConvertJSONOutputToBinary()`
* PA `--input-tensor-format` and `--output-tensor-format` CLI options
* PA perf_utils.cc `ParseTensorFormat()` function
* Triton Server end-to-end `L0_http` test usage of json tensor format (via adding options to an example executable used in `L0_http`)

Add testing for json tensor format

---

src/c++/perf_analyzer/constants.h
src/c++/perf_analyzer/inference_profiler.cc
src/c++/perf_analyzer/inference_profiler.h

Updated delayed reporting. 
Now whenever any requests are delayed, the Avg send request rate will be printed along with a warning that includes the percent of requests that were delayed. This should provide more context for users when PA is overloaded.

improve delay reporting

---

src/c++/perf_analyzer/data_loader.cc
src/c++/perf_analyzer/data_loader.h
src/c++/perf_analyzer/test_dataloader.cc

Multiple input-data files can be supplied to PA. This is legal, but bad things happen if there is a mixture of objects (single-stream) and arrays (multi-stream).  This PR explicitly tests the cases of all-objects and all-arrays, and also explicitly fails on a mixture of the two.

Test multiple input data

---

src/c++/perf_analyzer/infer_context.cc
src/c++/perf_analyzer/infer_context.h
src/c++/perf_analyzer/inference_profiler.cc
src/c++/perf_analyzer/perf_utils.h
src/c++/perf_analyzer/test_inference_profiler.cc
src/c++/perf_analyzer/test_load_manager.cc

Update time stamp vector to now include a list of end times for responses. 
For now, to preserve the functionality of PA, the final entry in the time stamp vector is used in place of the previous single entry to the end times. This should make this change invisible to the current implementation until the final response parameter can get bubbled up from the grpc client.

Update time stamp vector to hold a list of response times

---

src/c++/perf_analyzer/data_loader.cc
src/c++/perf_analyzer/data_loader.h
src/c++/perf_analyzer/infer_context.cc
src/c++/perf_analyzer/infer_data.h
src/c++/perf_analyzer/infer_data_manager.cc
src/c++/perf_analyzer/infer_data_manager_base.cc
src/c++/perf_analyzer/infer_data_manager_base.h
src/c++/perf_analyzer/infer_data_manager_shm.cc
src/c++/perf_analyzer/infer_data_manager_shm.h
src/c++/perf_analyzer/mock_infer_data_manager.h
src/c++/perf_analyzer/tensor_data.h
src/c++/perf_analyzer/test_dataloader.cc

Creates a struct TensorData to wrap up the data_ptr, size, and valid bit into one. 
Cleans up many function prototypes by using the new struct 
Removes ugly workaround that had code looking for "data_ptr not null but byte_size == 0" for the case of valid data with 0 shape (now it just relies on the valid bit)

Clean up dataloader functions

---

src/python/library/tritonclient/http/aio/__init__.py

`aiohttp.ClientResponse` object has [`status`](https://docs.aiohttp.org/en/stable/client_reference.html#aiohttp.ClientResponse.status) instead of `status_code`

Fix aio HTTP status retrieval

---

src/c++/library/common.cc
src/c++/library/common.h
src/c++/library/grpc_client.cc
src/c++/library/http_client.cc
src/c++/perf_analyzer/client_backend/client_backend.h
src/c++/perf_analyzer/client_backend/mock_client_backend.h
src/c++/perf_analyzer/client_backend/triton/triton_client_backend.cc
src/c++/perf_analyzer/client_backend/triton/triton_client_backend.h
src/c++/perf_analyzer/infer_context.cc
src/c++/perf_analyzer/inference_profiler.cc
src/c++/perf_analyzer/inference_profiler.h
src/c++/perf_analyzer/load_manager.h
src/c++/perf_analyzer/mock_inference_profiler.h
src/c++/perf_analyzer/mock_load_manager.h
src/c++/perf_analyzer/perf_utils.h
src/c++/perf_analyzer/test_inference_profiler.cc

* Skips null response latency recording
* Calculates responses sent per second in InferenceProfiler

Calculate response throughput metric

---

src/c++/perf_analyzer/perf_utils.cc
src/c++/perf_analyzer/perf_utils.h

Follow up PR addressing the removal of unused function from [#362](https://github.com/triton-inference-server/client/pull/362)

Remove an unused function `ShapeTensorValuesToString()` in perf_utils

---

src/python/library/tritonclient/grpc/_infer_input.py
src/python/library/tritonclient/http/_infer_input.py

Return self in InferInput setters for chain-initialization

---

src/c++/perf_analyzer/infer_context.cc
src/c++/perf_analyzer/inference_profiler.cc
src/c++/perf_analyzer/request_record.h
src/c++/perf_analyzer/test_inference_profiler.cc
src/c++/perf_analyzer/test_load_manager.cc

Null responses were accidentally not included in raw timestamps vector for each request. We actually want those in the profile export. This adds them in, but still excludes them from response throughput calculation.

Fix bug where null response were accidentally excluded from profile export

---

src/c++/perf_analyzer/command_line_parser.cc
src/c++/perf_analyzer/command_line_parser.h
src/c++/perf_analyzer/docs/cli.md
src/c++/perf_analyzer/test_command_line_parser.cc

Checks made on the inputs are:
- Protect unsigned parameters against negative inputs (and potential overflow)
- Validate file path
- Validate non-negative integer range inputs (e.g. `start:end`)
- Check for valid type/option
- Rephrase all error messages to include the flag name for better clarity

Improve sanity checking and error messages in PerfAnalyzer CLI

---

src/python/library/tritonclient/http/_utils.py

This updates `_get_inference_request` to always return the request body as `bytes`, as per the `InferenceServerClient .generate_request_body` docstring.
Issues are disabled for this repository, so I apologize if it isn't appropriate to open PRs here!

Ensure request body is always returned as bytes

---

src/c++/perf_analyzer/report_writer.cc

There are a few places where trailing commas are left depending on config flags:
- [Here](https://github.com/triton-inference-server/client/blob/d257c0e5c3de6e15d6ef289ff2b96cecd0a69b5f/src/c%2B%2B/perf_analyzer/report_writer.cc#L106) if should_output_metrics is false
- When [writing metrics](https://github.com/triton-inference-server/client/blob/d257c0e5c3de6e15d6ef289ff2b96cecd0a69b5f/src/c%2B%2B/perf_analyzer/report_writer.cc#L389)
Ideally there should be some unit tests to validate the produced CSVs are actually valid CSV files (no trailing delimiters), but verified locally here:
```
./perf_analyzer -m id --shape INPUT0:1,1 --concurrency 1:2 -f report.csv
./perf_analyzer -m id --shape INPUT0:1,1 --concurrency 1:2 -f report_metrics.csv --collect-metrics
./perf_analyzer -m id --shape …
```

Fix trailing comma in CSV for verbose_csv and collect_metrics modes

---

src/java-api-bindings/scripts/install_dependencies_and_build.sh

Related to: https://github.com/triton-inference-server/server/pull/6296/

Update client build script to be source of truth for java related installations

---

src/python/library/tritonclient/grpc/_infer_stream.py
src/python/library/tritonclient/grpc/_utils.py

`rpc_error.cancelled` is  True for restricted RPCs as well.

Fix L0_grpc

---

src/c++/perf_analyzer/command_line_parser.cc
src/c++/perf_analyzer/command_line_parser.h
src/c++/perf_analyzer/docs/cli.md
src/c++/perf_analyzer/perf_analyzer.cc
src/c++/perf_analyzer/perf_utils.h
src/c++/perf_analyzer/test_command_line_parser.cc

Add two new command line options to enable periodic concurrency mode in Perf Analyzer:
- `--periodic-concurrency-range=<start:end:step>`
- `--request-period=<n>`
- `--request-parameter=<name:value:type>`
The new command line options will users to launch Perf Analyzer in periodic concurrency mode and can be used as in the following command:
```bash
perf_analyzer -m <model_name> -i grpc --aync --streaming \
--profile-export-file profile.json \
--periodic-concurrency-range 20:400:10 \
--request-period 50 \
--request-parameter max_tokens:256:int
```
> **Note**
> The periodic concurrency mode only supports the decoupled models, so the user must use gRPC streaming in order to launch it on PA. Additionally, the user must also specify a file where PA could dump all the profiled data since there …

Add new command line options to enable periodic concurrency mode

---

src/c++/perf_analyzer/periodic_concurrency_worker.cc

Catches when request receives final response without having first reached the end of the request period. Throws error with suggested solution to avoid infinite loop. User error. User must provide request period less than or equal to the max tokens the model will return per request.

Throw exception when request period larger than max tokens rather than infinite loop

---

src/c++/library/common.h
src/c++/library/grpc_client.cc
src/c++/perf_analyzer/client_backend/client_backend.h
src/c++/perf_analyzer/client_backend/triton/triton_client_backend.cc
src/c++/perf_analyzer/command_line_parser.cc
src/c++/perf_analyzer/command_line_parser.h
src/c++/perf_analyzer/concurrency_manager.cc
src/c++/perf_analyzer/concurrency_manager.h
src/c++/perf_analyzer/custom_load_manager.cc
src/c++/perf_analyzer/custom_load_manager.h
src/c++/perf_analyzer/infer_data_manager.cc
src/c++/perf_analyzer/infer_data_manager.h
src/c++/perf_analyzer/infer_data_manager_base.cc
src/c++/perf_analyzer/infer_data_manager_base.h
src/c++/perf_analyzer/infer_data_manager_factory.h
src/c++/perf_analyzer/infer_data_manager_shm.cc
src/c++/perf_analyzer/infer_data_manager_shm.h
src/c++/perf_analyzer/load_manager.cc
src/c++/perf_analyzer/load_manager.h
src/c++/perf_analyzer/mock_infer_data_manager.h
src/c++/perf_analyzer/perf_analyzer.cc
src/c++/perf_analyzer/perf_utils.h
src/c++/perf_analyzer/periodic_concurrency_manager.h
src/c++/perf_analyzer/request_rate_manager.cc
src/c++/perf_analyzer/request_rate_manager.h
src/c++/perf_analyzer/test_command_line_parser.cc
src/c++/perf_analyzer/test_concurrency_manager.cc
src/c++/perf_analyzer/test_custom_load_manager.cc
src/c++/perf_analyzer/test_load_manager.cc
src/c++/perf_analyzer/test_request_rate_manager.cc

Add support for passing parameters from the command line to triton server via the grpc protocol

add request parameters

---

src/c++/perf_analyzer/command_line_parser.cc

While testing out the new periodic concurrency mode, @matthewkotila and I have noticed that the **5-th** request would consistently hang forever and wait for response from the server. 
**The issue was that `max_threads_` was set default to 4**, and if this value was less than the concurrency value, the request created after the `max_threads_` number of times (e.g. the 5-th one in our case) will be missing input data. This is because the infer_data_manager that prepares all the input data, uses `max_threads_` count to generate the input data and populate the requests with the input data. And I believe this is why the server - when it received the empty 5-th request - did not pass it down to the model.
The fix checks the `max_threads_` value against the concurrency range (similar to [how …

🐛 Fix request hanging in periodic concurrency greater than 4

---

src/c++/perf_analyzer/docs/llm.md

Add third part to guide for testing continuous batch size on token-to-token latency.

Add continus batch size benchmark to LLM guide

---

README.md

Document gRPC client-side request cancellation

---

src/java-api-bindings/scripts/install_dependencies_and_build.sh

Addresses: https://github.com/triton-inference-server/client/pull/395
To be merged after https://github.com/bytedeco/javacpp-presets/pull/1420

change logic to true=1

---

README.md
src/python/library/tritonclient/grpc/aio/__init__.py

Related PR: https://github.com/triton-inference-server/server/pull/6408
This PR adds the ability to cancel AsyncIO gRPC stream requests. There are interface changes on `stream_infer()`, but the "syntax" on the old and new interfaces are the same, so the amount of code breaking should be minimal if any.

Add ability to cancel AsyncIO gRPC stream requests

---

README.md
src/python/library/tritonclient/grpc/aio/__init__.py

* Add ability to cancel AsyncIO gRPC stream or non-stream requests
* Add docs on AsyncIO request cancellation
* Improve AsyncIO docs
* Improve example code styling
* Skip await on documentation
---------

Add ability to cancel AsyncIO gRPC stream requests (#417)

---

src/c++/perf_analyzer/command_line_parser.cc
src/c++/perf_analyzer/test_command_line_parser.cc

Changing `CLParser` to throw exception instead of exit the program when the usage is called. This is to match the behavior of the test code with that of the production code. This greatly simplifies the test code as we don't need to check if the usage is called and match the error message separately.
_Without_ the change, the test code needs
- `REQUIRE_NOTHROW` to run the parser
- `CHECK` to check if usage is called
- `CHECK_STRING` to check if the error messages match
_With_ the change, the test code only needs
- `CHECK_THROWS_WITH_AS` to run the parser and check the error messages.

Change CLParser to throw exception instead of exit when usage called

---

src/python/library/build_wheel.py

Distutils is being deprecated. Replace the use of copy_tree with the shutil version.
Related server PR: https://github.com/triton-inference-server/server/pull/6190
Related model analyzer PR: https://github.com/triton-inference-server/model_analyzer/pull/746

Replace deprecated distutils 

---

src/c++/perf_analyzer/docs/examples/profile.py

In the recent PR #431, the `token_to_token_latencies` list was getting reset for every new requests. We instead want to collect every token to token latencies across all the requests. 
This bug only affects Avg total token-to-token latency metric.

[Bug fix] Avoid resetting token-to-token latencies list

---

src/python/library/tritonclient/grpc/aio/__init__.py

Should fix:
> L0_grpc--base: Protocol message ModelStatisticsRequest has no "timeout" field

Put timeout in RPC call, not protobuf object

---

src/c++/perf_analyzer/docs/examples/profile.py
src/c++/perf_analyzer/docs/llm.md

- Support TRTLLM (e.g. `ensemble`) model in the benchmark script
- Use Triton vLLM backend and update the outdated doc

Support TRTLLM model in the benchmark script

---

src/c++/perf_analyzer/infer_context.cc

Takes the thread ID and sets that to the upper 16 bits of the 64-bit-converted-to-string request ID. Takes the thread-local request ID and sets that to the lower 48 bits.

Implement unique request IDs across threads

---

CMakeLists.txt
src/c++/library/CMakeLists.txt

This PR is one of the series PRs to update Triton to C++17 standard.
This PR sets Triton's min CXX standard to 17 and uses `TRITON_MIN_CXX_STANDARD` either newly set or from cmake cache

Bump min cxx standard to 17

---

src/c++/perf_analyzer/genai-pa/README.md
src/c++/perf_analyzer/genai-pa/genai_pa/.gitignore
src/c++/perf_analyzer/genai-pa/genai_pa/__init__.py
src/c++/perf_analyzer/genai-pa/genai_pa/constants.py
src/c++/perf_analyzer/genai-pa/genai_pa/main.py
src/c++/perf_analyzer/genai-pa/genai_pa/parser.py
src/c++/perf_analyzer/genai-pa/genai_pa/wrapper.py
src/c++/perf_analyzer/genai-pa/pyproject.toml
src/c++/perf_analyzer/genai-pa/tests/test_cli.py
src/c++/perf_analyzer/genai-pa/tests/test_library.py

Install
```
rmccormick@ced35d0-lcedt:~/triton/jira/genaipa/client/src/c++/perf_analyzer/genai-pa$ pip install .
Defaulting to user installation because normal site-packages is not writeable
Processing /home/rmccormick/triton/jira/genaipa/client/src/c++/perf_analyzer/genai-pa
Installing build dependencies ... done
Getting requirements to build wheel ... done
Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: rich in /home/rmccormick/.local/lib/python3.10/site-packages (from genai-pa==0.0.1) (13.5.2)
Requirement already satisfied: numpy in /home/rmccormick/.local/lib/python3.10/site-packages (from genai-pa==0.0.1) (1.25.2)
Requirement already satisfied: markdown-it-py>=2.2.0 in /home/rmccormick/.local/lib/python3.10/site-packages (from rich->genai-pa==0.0.1) (3.0.0) …
```

Add boilerplate for parsing, testing, and wrapping PA

---

src/c++/perf_analyzer/genai-pa/genai_pa/parser.py
src/c++/perf_analyzer/genai-pa/pyproject.toml
src/c++/perf_analyzer/genai-pa/tests/test_cli.py

Built off of Ryan's test files, here are the first few unit tests for the GenAI-PA CLI. These test all the current CLI args.
To run, you can call `pip install .` and `pytest tests/` in `perf_analyzer/genai_pa`.
This is the draft for CLI unit testing. If we want to write unit tests that actually check output, I'll need to mock the server (or copy over MA's mock) so that we can test that the subprocess call returns the expected output. Given the scope of the CLI at present, I think that may be overkill and we should be testing that the subprocess call is correct, then have end-to-end testing to show that it works as expected with a Triton server running.

Add CLI unit tests for GenAI-PA CLI

---

src/c++/perf_analyzer/genai-pa/genai_pa/constants.py
src/c++/perf_analyzer/genai-pa/genai_pa/llm_inputs/llm_inputs.py
src/c++/perf_analyzer/genai-pa/tests/test_llm_inputs.py

I've updated the API, added a generic JSON framework to store the intermediate data and added methods to convert to vLLM format.
Here's an example output of HF input to vLLM output. Both role text strings (system/user) are concatenated to form the text input.
```
{
"data": [
{
"text_input": [
"You are an AI assistant. You will be given a task. You must generate a detailed and long answer.",
"Generate an approximately fifteen-word sentence that describes all this data: Midsummer House eatType restaurant; Midsummer House food Chinese; Midsummer House priceRange moderate; Midsummer House customer rating 3 out of 5; Midsummer House near All Bar One"
],
"stream": [
true
]
},
]
}

LlmInputs - Updated API + generic framework + convert to vLLM format

---

src/c++/perf_analyzer/infer_context.cc
src/c++/perf_analyzer/profile_data_exporter.cc
src/c++/perf_analyzer/request_record.h
src/c++/perf_analyzer/test_profile_data_collector.cc

Fix issue where collected data was pointers to data that could be changed/overwritten

Fix data export

---

src/c++/perf_analyzer/genai-pa/genai_pa/llm_inputs/llm_inputs.py
src/c++/perf_analyzer/genai-pa/tests/test_llm_inputs.py

Created a new output format: OPENAI_COMPLETIONS
Here is an example json output:
```
{
"data": [
{
"payload": [
{
"prompt": [
"You will be given a definition of a task first, then some input of the task.\nThis task is about using the specified sentence and converting the sentence to Resource Description Framework (RDF) triplets of the form (subject, predicate object). The RDF triplets generated must be such that the triplets accurately capture the structure and semantics of the input sentence. The input is a sentence and the output is a list of triplets of the form [subject, predicate, object] that capture the relationships present in the sentence. When a sentence has more than 1 RDF triplet possible, the output must contain all of them.\n\nAFC Ajax (amateurs)'s ground is Sportpark De …
```

Llm inputs - Add openai legacy completions output format

---

src/c++/perf_analyzer/genai-pa/genai_pa/llm_inputs/llm_inputs.py
src/c++/perf_analyzer/genai-pa/tests/test_llm_inputs.py

Added support for trtLLM endpoints.
Here's a sample output:
```
{
"data": [
{
"text_input": [
"You will be given a definition of a task first, then some input of the task.\nThis task is about using the specified sentence and converting the sentence to Resource Description Framework (RDF) triplets of the form (subject, predicate object). The RDF triplets generated must be such that the triplets accurately capture the structure and semantics of the input sentence. The input is a sentence and the output is a list of triplets of the form [subject, predicate, object] that capture the relationships present in the sentence. When a sentence has more than 1 RDF triplet possible, the output must contain all of them.\n\nAFC Ajax (amateurs)'s ground is Sportpark De Toekomst where Ajax Youth Academy …
```

LlmInputs - trtllm output format support

---

src/c++/perf_analyzer/genai-pa/genai_pa/llm_metrics.py
src/c++/perf_analyzer/genai-pa/genai_pa/main.py

This pull request formats the printed metrics produced by GenAi-PA. While we only have two metrics so far, it aims to future-proof metrics so that there is less work as new metrics are added.
Note that the below output seems to be wrong (the number of seconds is too high). This pull request is only focused on formatting. The computation will either be in a separate ticket or be added here later, if the team decides that is easier.
Output:

Add formatting for GenAi-PA report

---

src/c++/perf_analyzer/genai-pa/genai_pa/llm_inputs/llm_inputs.py
src/c++/perf_analyzer/genai-pa/tests/test_llm_inputs.py

I've fixed the output formatting for all 4 endpoints.
Also added in a check (and unit testing) for the case where add_model_name flag is set and model_name is not specified.

Llm inputs - fix output formatting

---

src/c++/perf_analyzer/genai-pa/genai_pa/llm_metrics.py
src/c++/perf_analyzer/genai-pa/genai_pa/main.py
src/c++/perf_analyzer/genai-pa/genai_pa/utils.py
src/c++/perf_analyzer/genai-pa/tests/test_llm_metrics.py

- Fix Triton response output parsing
- Support OpenAI chat completion response output (both stream and non-stream)
- Support legacy OpenAI completion response output
- Add test case for OpenAI chat completion response
- Add `num_output_tokens` metrics & statistics
**NOTE**: Currently everything is located at `llm_metrics.py` and a separate PR will handle properly locating these classes into different modules since it will hide the changes made in this PR.

Support parsing profile data JSON output of both Triton and OpenAI

---

src/c++/perf_analyzer/genai-pa/genai_pa/llm_metrics.py
src/c++/perf_analyzer/genai-pa/genai_pa/main.py
src/c++/perf_analyzer/genai-pa/genai_pa/parser.py

This pull request cleans up the GenAi-PA report table and exports the more detailed metrics to a CSV (e.g. more percentile options).
Since we are requiring the export file due to PA returning it, this clarifies the wording. For simplicity, since the PA export is being saved, the GenAi-PA one will be as well. If we remove the PA export file being written in the future, we can also look at making the GenAi-PA CSV being optional for users who want to disable the exports.
Report with highlights shown (excluding inter-token latency due to this being with streaming disabled):
CSV with all calculated percentiles shown (excluding inter-token latency due to this being with streaming disabled):

Export GenAi-PA results to CSV file

---

src/c++/perf_analyzer/genai-pa/genai_pa/llm_metrics.py

- When calculating ITL, set number of token to default to 1 when the response is empty (for now)
- Convert latency units from nanosecond to second in order to avoid near-zero throughput metrics.

Fix divide by zero and unit conversion for throughput display

---

src/c++/perf_analyzer/genai-pa/genai_pa/llm_metrics.py

Updates the formatting for GenAi-PA:
1. For throughput metrics, show 2 significant figures.
2. For throughput metrics, only one value matters. Take these metrics out of the main table.
3. For the streaming case, time to first token and response latency are the same, so do not show time to first token.
New format for output table:
New format for CSV export:

Update GenAi-PA formatting for throughput and streaming metrics 

---

src/c++/perf_analyzer/genai-pa/genai_pa/llm_metrics.py

If the response is empty, then `i` is undefined

Fix handling of empty response

---

CMakeLists.txt

As the title suggests, this PR provides a reasonable default for the `TRITON_REPO_ORGANIZATION` cmake parameter so it doesn't have to be specified when building every time.

Adding default for TRITON_REPO_ORGANIZATION

---

src/c++/perf_analyzer/genai-pa/tests/test_llm_metrics.py

- Add whitespace to triton response outputs to avoid valid chars getting removed
- Convert throughput unit from nanosecond to second

Fix failing test_llm_metrics.py

---

src/c++/perf_analyzer/genai-perf/genai_perf/main.py
src/c++/perf_analyzer/genai-perf/genai_perf/parser.py
src/c++/perf_analyzer/genai-perf/tests/test_cli.py

- Require passthrough args to follow separator ("--")
- Use parse_args instead of parse_known_args to avoid hiding errors
- Use monkeypatch to mock CLI args in testing
Tests passing:

Fix passthrough arg handling and testing

---

src/c++/perf_analyzer/genai-perf/genai_perf/llm_metrics.py

Add output token throughput per request metric to be displayed _inside_ the statistics table with all the aggregated stats.

Fix output token throughput per request metric display

---

src/c++/perf_analyzer/genai-perf/genai_perf/llm_metrics.py
src/c++/perf_analyzer/genai-perf/genai_perf/main.py
src/c++/perf_analyzer/genai-perf/genai_perf/parser.py
src/c++/perf_analyzer/genai-perf/tests/test_cli.py

Use the default load level in PA (concurrency 1) if load level is not provided in GenAi-PA.
Tested with:
Result:
Unit testing passed:

Make load level optional for GenAi-PA

---

src/c++/perf_analyzer/genai-perf/genai_perf/parser.py
src/c++/perf_analyzer/genai-perf/genai_perf/wrapper.py
src/c++/perf_analyzer/genai-perf/tests/test_cli.py
src/c++/perf_analyzer/genai-perf/tests/test_cmd_builder.py

GenAi-Perf handles different kinds of services and endpoints, resulting in conditional expectations for the arguments provided by the user. This pull request tests that logic.
It also adds a separate test for the command builder step, which does postprocessing on the command line arguments received and builds the command run. This ensures the conditional logic used in the postprocessing step is validated in our unit testing.
Command builder test:
CLI test:

Add unit testing for conditional parsing in GenAi-Perf

---

src/c++/perf_analyzer/genai-perf/genai_perf/llm_metrics.py
src/c++/perf_analyzer/genai-perf/tests/test_llm_metrics.py

Removes last one or two responses of chat completion API that has either empty `delta` or null response:
Empty `delta`:
```
data: {"id":"chatcmpl-92iz6RYuQb8FcGT2QrpQ6vQyRfWUA","object":"chat.completion.chunk","created":1710436604,"model":"gpt-3.5-turbo-0125","system_fingerprint":"fp_4f2ebda25a","choices":[{"index":0,"delta":{},"logprobs":null,"finish_reason":"length"}]}
```
Null response:
```
data: [DONE]
```

Remove final empty/null responses in OpenAI API

---

src/c++/perf_analyzer/genai-perf/genai_perf/llm_inputs/llm_inputs.py
src/c++/perf_analyzer/genai-perf/genai_perf/main.py
src/c++/perf_analyzer/genai-perf/genai_perf/parser.py
src/c++/perf_analyzer/genai-perf/genai_perf/wrapper.py
src/c++/perf_analyzer/genai-perf/tests/test_cli.py
src/c++/perf_analyzer/genai-perf/tests/test_cmd_builder.py
src/c++/perf_analyzer/genai-perf/tests/test_llm_inputs.py

Reorganize the CLI args to make the help menu easier to navigate.
Unit testing:
Updated help menu:

Reorganize CLI args in GenAi-Perf

---

src/c++/perf_analyzer/genai-perf/genai_perf/llm_metrics.py
src/c++/perf_analyzer/genai-perf/tests/test_llm_metrics.py

Old format:
```
Statistic,avg,min,max,p99,p95,p90,p75,p50,p25
time_to_first_token(ns),4238735,3367978,6702240,6371118,5344958,5006259,4841394,4146648,3484484
inter_token_latency(ns),27202264,3849435,138324924,28283424,27737593,27469154,27067290,26979956,26926962
request_latency(ns),3363927003,3367978,14238834483,14091273510,13740917508,13692672723,3752510140,4846258,3612270
num_output_token,126,0,584,562,509,505,135,0,0
output_token_throughput(per sec),36.37
request_throughput(per sec),0.29
```
New format:
```
Metric,avg,min,max,p99,p95,p90,p75,p50,p25
Time to First Token (ns),4238735,3367978,6702240,6371118,5344958,5006259,4841394,4146648,3484484
Inter Token Latency (ns),27202264,3849435,138324924,28283424,27737593,27469154,27067290,26979956,26926962
Request Latency …
```

Update csv output format

---

src/c++/perf_analyzer/genai-perf/genai_perf/test_end_to_end.py
src/c++/perf_analyzer/genai-perf/genai_perf/wrapper.py

Pass the generated input data file to PA
Ignore input-dataset (don't pass it along to PA)
Update e2e testing script (which will be removed soon)

Fix issue where input data wasn't provided to PA

---

src/c++/perf_analyzer/genai-perf/genai_perf/llm_inputs/llm_inputs.py
src/c++/perf_analyzer/genai-perf/genai_perf/llm_inputs/synthetic_prompt_generator.py
src/c++/perf_analyzer/genai-perf/genai_perf/llm_metrics.py
src/c++/perf_analyzer/genai-perf/genai_perf/main.py
src/c++/perf_analyzer/genai-perf/genai_perf/parser.py
src/c++/perf_analyzer/genai-perf/genai_perf/tokenizer.py
src/c++/perf_analyzer/genai-perf/genai_perf/wrapper.py
src/c++/perf_analyzer/genai-perf/tests/test_llm_inputs.py
src/c++/perf_analyzer/genai-perf/tests/test_tokenizer.py

User can add --tokenizer to the command line and the string is used to pull down a tokenizer from huggingface's autotokenizer module.
On success, the tokenizer is passed around as an object.
On failure, an error message is raised showing that the model is not available.
Default is set to llama via
`DEFAULT_TOKENIZER = "hf-internal-testing/llama-tokenizer"`
Testing ensures that the default and a second valid non default tokenizer work, while an incorrect model name, raises an error.

add tokenizer option

---

src/c++/perf_analyzer/genai-perf/genai_perf/wrapper.py
src/c++/perf_analyzer/genai-perf/tests/test_wrapper.py

This pull request makes it so that GenAi-perf no longer prints perf_analyzer output if the verbose flag is not passed.
Verbose flag not supplied:
Verbose flag supplied (`-v`):
Verbose flag supplied (`--verbose`):

If verbose flag is not passed to GenAi-Perf, do not print PA output

---

src/c++/library/common.cc
src/c++/library/common.h
src/c++/perf_analyzer/client_backend/client_backend.cc
src/c++/perf_analyzer/client_backend/client_backend.h
src/c++/perf_analyzer/client_backend/openai/openai_infer_input.cc
src/c++/perf_analyzer/client_backend/openai/openai_infer_input.h
src/c++/perf_analyzer/client_backend/triton/triton_client_backend.cc
src/c++/perf_analyzer/client_backend/triton/triton_client_backend.h
src/c++/perf_analyzer/infer_context.cc
src/c++/perf_analyzer/infer_context.h
src/c++/perf_analyzer/profile_data_exporter.cc
src/c++/perf_analyzer/profile_data_exporter.h
src/c++/perf_analyzer/request_record.h
src/c++/perf_analyzer/test_inference_profiler.cc
src/c++/perf_analyzer/test_load_manager.cc
src/c++/perf_analyzer/test_profile_data_collector.cc
src/c++/perf_analyzer/test_profile_data_exporter.cc

Example:
```json
{
"experiments": [
{
"experiment": {
"mode": "concurrency",
"value": 1
},
"requests": [
{
"timestamp": 10,
"request_input": {
"text_input": "o\u0000\u0000\u0000Randomly stream lines from the following text with 150 output tokens. Don't generate eos tokens:\n\nappertaining ",
"stream": true,
},
"response_timestamps": [ 1, 2 ],
"response_outputs": [
{"text_output": "..."},
{"text_output": "..."}
]
},
],
"window_boundaries": [ ... ]
}
],
"version": "0.0.0"
}
```

Add request input to profile export data

---

src/c++/perf_analyzer/genai-perf/README.md
src/c++/perf_analyzer/genai-perf/genai_perf/llm_inputs/llm_inputs.py
src/c++/perf_analyzer/genai-perf/genai_perf/main.py
src/c++/perf_analyzer/genai-perf/genai_perf/parser.py
src/c++/perf_analyzer/genai-perf/genai_perf/wrapper.py
src/c++/perf_analyzer/genai-perf/tests/test_cli.py
src/c++/perf_analyzer/genai-perf/tests/test_llm_inputs.py

This will allow users to pass in additional inputs beyond those in the model. This is useful for adding support to different backends/endpoints that have different arguments they support without hardcoding each one into GenAi-Perf.
This has been tested for Triton+TRT-LLM, Triton+vLLM, vLLM+OpenAI (both endpoints). If we wanted to drop support for `--streaming`, we could so since that would now be supported via `--extra-inputs` (e.g. `--extra-inputs stream:True`).
When a non-existent input name is given, no error is raised and GenAi-Perf works as if it was not provided. I created a follow-up ticket (TMA-1799) to investigate if PA is not raising an error when input data for non-existent inputs is provided in an input data JSON. That ticket aims to make sure an error is raised in PA and …

Allow extra request inputs

---

src/c++/perf_analyzer/genai-perf/genai_perf/llm_metrics.py
src/c++/perf_analyzer/genai-perf/tests/test_llm_metrics.py

- Store inter token latencies per request in Metrics object to reuse them in the plot generation
- Add accessor to underlying Metrics object and statistics data in Statistics class
```python
stats = Statistics(...)
print(stats.metrics)
print(stats.data)
```

Extend Statistics and Metrics for visualization

---

src/c++/perf_analyzer/genai-perf/genai_perf/llm_inputs/llm_inputs.py
src/c++/perf_analyzer/genai-perf/tests/test_llm_inputs.py

The behavior of max-tokens in TRT-LLM was correct (if the user passes in `--extra-inputs max_tokens:<number_of_tokens>`, that value is used), but this was not explicit and would break if someone switched the order of adding required and optional JSON inputs. This PR makes this behavior explicit and clear, plus it adds testing to ensure the correct value is parsed for max_tokens.

Make TRT-LLM max_tokens behavior explicit in GenAi-Perf

---

src/c++/perf_analyzer/genai-perf/genai_perf/llm_metrics.py
src/c++/perf_analyzer/genai-perf/genai_perf/main.py
src/c++/perf_analyzer/genai-perf/tests/test_llm_metrics.py

Passed e2e tests for both triton (trtllm, vllm) and openai endpoints.
Sample std output:
Sample csv output:
```
Metric,avg,min,max,p99,p95,p90,p75,p50,p25
Time To First Token (ns),11520474,7129972,31636530,25133016,21681889,19220078,12972134,11192398,7543069
Inter Token Latency (ns),948192,39108,8515906,2678516,1496222,1387632,1017759,912862,672564
Request Latency (ns),49809627,13591020,88391910,83426245,74369309,66837708,57967980,51241493,37371832
Num Output Token,45,4,63,53,50,49,47,46,44
Num Input Token,44,40,52,51,50,49,44,43,42
Metric,Value
Output Token Throughput (per sec),899.94
Request Throughput (per sec),19.97
```

Add number of input tokens metric

---

src/c++/perf_analyzer/genai-perf/README.md
src/c++/perf_analyzer/genai-perf/genai_perf/llm_inputs/llm_inputs.py
src/c++/perf_analyzer/genai-perf/genai_perf/llm_inputs/synthetic_prompt_generator.py
src/c++/perf_analyzer/genai-perf/genai_perf/parser.py
src/c++/perf_analyzer/genai-perf/genai_perf/wrapper.py
src/c++/perf_analyzer/genai-perf/tests/test_cli.py
src/c++/perf_analyzer/genai-perf/tests/test_llm_inputs.py

The synthetic expected output tokens option helped provide a way for users to recommend an output token length to GenAi-Perf via prompt engineering. However, it did not guarantee a set number of expected output tokens will be generated.
Now that we are adding a way to precisely set the output token count mean and standard deviation, a user can always just set the output token mean to be the number of output tokens they want and the standard deviation to 0 for the same effect. As a result, we can remove the expected output tokens option to remove overlap and provide an option with increased accuracy.

Remove synthetic expected output tokens option

---

src/c++/perf_analyzer/genai-perf/genai_perf/llm_inputs/llm_inputs.py
src/c++/perf_analyzer/genai-perf/tests/test_llm_inputs.py

TRT-LLM does not support ignore_eos. Using min_length guarantees that the requested number of tokens is generated.

Switch TRT-LLM to use min_length instead of ignore_eos

---

src/c++/perf_analyzer/genai-perf/genai_perf/llm_inputs/llm_inputs.py
src/c++/perf_analyzer/genai-perf/tests/test_llm_inputs.py

Now that [min_tokens](https://github.com/triton-inference-server/vllm_backend/pull/37) are supported in vLLM after the vLLM version [upgrade](https://github.com/triton-inference-server/vllm_backend/pull/38), switch to using them for more accurate token counts.

Use min_tokens instead of ignore_eos in vLLM for improved accuracy

---

src/c++/perf_analyzer/genai-perf/.gitignore
src/c++/perf_analyzer/genai-perf/genai_perf/constants.py
src/c++/perf_analyzer/genai-perf/genai_perf/graphs/base_plot.py
src/c++/perf_analyzer/genai-perf/genai_perf/graphs/box_plot.py
src/c++/perf_analyzer/genai-perf/genai_perf/graphs/heat_map.py
src/c++/perf_analyzer/genai-perf/genai_perf/graphs/plot_manager.py
src/c++/perf_analyzer/genai-perf/genai_perf/graphs/scatter_plot.py
src/c++/perf_analyzer/genai-perf/genai_perf/llm_metrics.py
src/c++/perf_analyzer/genai-perf/genai_perf/main.py
src/c++/perf_analyzer/genai-perf/pyproject.toml
src/c++/perf_analyzer/genai-perf/tests/test_llm_inputs.py

* Initial ttft box plot implementation
* Add request latency chart
* Add heatmap graph
* Add scatter plot graph
* Add base class for plots
* Update requirements
* Add plot manager and refactor to use a base class
* Add parquet output to genai-perf
* Use new plot manager class and update gitignore to ignore artifacts directory
* Add compression to parquet files
* Remove unused imports
* Fix annotations for box plots
* Rename labels and update another feedback
* Fix title and formatting
* Add comment for deep copy
* Update plots to preprocess data and use a common API
* Uncomment run method and error logging
* Remove * in arg list for plots
* Disable failing test: test_random_synthetic

add visualizations (#558)

---

src/c++/perf_analyzer/client_backend/triton_c_api/shared_memory_manager.cc
src/c++/perf_analyzer/client_backend/triton_c_api/shared_memory_manager.h
src/c++/perf_analyzer/client_backend/triton_c_api/triton_loader.cc

Echos Server PR: triton-inference-server/server#7083
Chery pick of: https://github.com/triton-inference-server/client/pull/565

Update shared memory bound checking for infer requests (#565)

---

src/c++/perf_analyzer/genai-perf/README.md
src/c++/perf_analyzer/genai-perf/genai_perf/llm_inputs/llm_inputs.py
src/c++/perf_analyzer/genai-perf/genai_perf/main.py
src/c++/perf_analyzer/genai-perf/genai_perf/parser.py
src/c++/perf_analyzer/genai-perf/genai_perf/wrapper.py
src/c++/perf_analyzer/genai-perf/tests/test_cli.py
src/c++/perf_analyzer/genai-perf/tests/test_llm_inputs.py

Create a parameter to allow users to request a minimum number of tokens for an expected output distribution. This is currently only supported in vLLM and TRT-LLM.

Make request output determinism optional

---

src/c++/library/grpc_client.cc

The gRPC client exposes a parameter that disables reusing a cached channel: `use_cached_channel`.
Setting this to false doesn't stop the channel (and mock) from being inserted to the internal channel cache. The problem with it being inserted to the map means the channel will only get destroyed once it's being replaced by another channel.
In our case we want the channel (and associated connection) to be closed as soon as the client using it is getting destroyed though, meaning we don't want to reuse the channel at all. I believe this is also consistent with the description for `use_cached_channel`:
> use_cached_channel If false, a new channel is created for each
/// new client instance. When true, re-use old channels from cache for new
/// client instances. The default value is true

Only store channel if use_cached_channel is true

---

src/c++/perf_analyzer/genai-perf/genai_perf/llm_inputs/llm_inputs.py
src/c++/perf_analyzer/genai-perf/genai_perf/wrapper.py
src/c++/perf_analyzer/genai-perf/tests/test_wrapper.py

Constructing a single command string to run PA becomes problem when one of the args is a string that contains a space. This causes the string content after the space to be missing from the final string. To avoid this problem, we can collect each args as a list of strings and pass that as an arg to subprocess call to run PA.

Construct PA command as a list of strings

---

src/c++/perf_analyzer/genai-perf/genai_perf/llm_metrics.py
src/c++/perf_analyzer/genai-perf/tests/test_llm_metrics.py

We used to ignore up to 2 final responses with no content. Now we will also ignore any initial responses with no content as well. This is possible for vllm, where it will send a quick response that only contains the role and no content, and should not be considered the first response token.

Ignore openai chunk responses with no content

---

src/c++/perf_analyzer/command_line_parser.cc
src/c++/perf_analyzer/docs/cli.md

Triton server no longer supports the trace file being changed after model load time, so remove this option in perf analyzer.

Remove trace file support in perf analyzer

---

src/c++/perf_analyzer/genai-perf/genai_perf/main.py

Currently, if someone calls GenAI-Perf and sets their own profile export file path/name, e.g.
```bash
genai-perf --profile-export-file my_profile_export.json ...
```
They will run into this error:
```
FileNotFoundError: [Errno 2] No such file or directory: 'profile_export.json' -> 'artifacts/data/profile_export.json' 
```
Because of these lines:
https://github.com/triton-inference-server/client/blob/f0ad3617b1775cc92fefa83a22d36b06d28a9adf/src/c%2B%2B/perf_analyzer/genai-perf/genai_perf/main.py#L123-L129
Those lines need to be updated to dynamically use whatever the profile export file path is set to, possibly different from the default (if the user specifies it)

Fix hardcoded profile export file name usage

---

.gitignore

Quick fix to update gitignore, I often accidentally include these output directories/files when committing

Update .gitignore to include GenAI-Perf artifacts

---

src/c++/perf_analyzer/genai-perf/README.md

Fix typo and missing option in docs

Fix typo and missing option in docs

---

src/c++/perf_analyzer/main.cc

For some reason this was missing making it much more difficult to understand why a non-zero exit code was given for cases where a PerfAnalyzerException is thrown with a message supplied in the constructor.
Tested manually and it works.

Print PerfAnalyzerException message on exit

---

src/c++/perf_analyzer/genai-perf/genai_perf/main.py
src/c++/perf_analyzer/genai-perf/genai_perf/plots/base_plot.py

Fixed a rename that was missed
Updated the artifact directory check to remove an edge case where the artifact directory is already created but the plots subdirectory was not. Now all directories are created but plots are only generated when the flag is given.

Fixed file path for plot generation

---

src/c++/perf_analyzer/genai-perf/genai_perf/llm_metrics.py

Add workaround for missing 'object' field from vLLM OpenAI Completions API response

Add workaround for missing 'object' field from vLLM OpenAI Completions API response

---

src/c++/perf_analyzer/mock_profile_data_exporter.h
src/c++/perf_analyzer/perf_analyzer.cc
src/c++/perf_analyzer/profile_data_exporter.cc
src/c++/perf_analyzer/profile_data_exporter.h
src/c++/perf_analyzer/test_profile_data_exporter.cc

Add `service_kind` and `endpoint` fields to the profile export JSON file:
```json
{
"experiments": { ... },
"version": "1.2.3",
"service_kind": "openai",
"endpoint": "v1/chat/completions"
}
```
This allows GenAI-Perf to gather profile metadata through the profile export file and is needed for GenAI-Perf `compare` subcommand to parse the profile export files directly.

Add more metadata to profile export JSON file

---

src/c++/perf_analyzer/genai-perf/README.md
src/c++/perf_analyzer/genai-perf/genai_perf/llm_inputs/llm_inputs.py
src/c++/perf_analyzer/genai-perf/genai_perf/main.py
src/c++/perf_analyzer/genai-perf/genai_perf/parser.py
src/c++/perf_analyzer/genai-perf/genai_perf/wrapper.py
src/c++/perf_analyzer/genai-perf/tests/test_cli.py
src/c++/perf_analyzer/genai-perf/tests/test_llm_inputs.py

- Added a new option --input-file
- Removed --prompt-source and now genai-perf infers the prompt source:
--input-dataset -> dataset
--input-file -> file
else synthetic
- Added error checking when multiple flags lead to unclear prompt source.
This maintains the default behavior of synthetic as the default.
Going forward, Genai-perf will move to infer more details and improve the UX.
- Inform user the source via a info command
sample prompt file:
llm_inputs.json when using an input file:

add --input-file support with new prompt source inference logic

---

src/c++/perf_analyzer/genai-perf/pyproject.toml

Missed a pyproject.toml update.
This will fix failing unit tests.

Fix missing dependency

---

src/python/library/tritonclient/utils/shared_memory/__init__.py
src/python/library/tritonclient/utils/shared_memory/shared_memory.cc

**Goal:** The python client was not properly deallocating dynamic memory when destroying shared memory regions. This PR bundle fixes the leak and adds an additional test case.
Server PR: https://github.com/triton-inference-server/server/pull/7172

Fix Python Shm Client Leak

---

src/c++/perf_analyzer/CMakeLists.txt
src/c++/perf_analyzer/client_backend/client_backend.h
src/c++/perf_analyzer/command_line_parser.cc
src/c++/perf_analyzer/command_line_parser.h
src/c++/perf_analyzer/concurrency_manager.cc
src/c++/perf_analyzer/concurrency_manager.h
src/c++/perf_analyzer/concurrency_worker.h
src/c++/perf_analyzer/custom_load_manager.cc
src/c++/perf_analyzer/custom_load_manager.h
src/c++/perf_analyzer/infer_context.h
src/c++/perf_analyzer/inference_profiler.cc
src/c++/perf_analyzer/inference_profiler.h
src/c++/perf_analyzer/load_manager.cc
src/c++/perf_analyzer/load_worker.cc
src/c++/perf_analyzer/load_worker.h
src/c++/perf_analyzer/perf_analyzer.cc
src/c++/perf_analyzer/periodic_concurrency_manager.cc
src/c++/perf_analyzer/periodic_concurrency_manager.h
src/c++/perf_analyzer/request_rate_manager.cc
src/c++/perf_analyzer/request_rate_manager.h
src/c++/perf_analyzer/request_rate_worker.h
src/c++/perf_analyzer/test_command_line_parser.cc
src/c++/perf_analyzer/test_concurrency_manager.cc
src/c++/perf_analyzer/test_custom_load_manager.cc
src/c++/perf_analyzer/test_request_rate_manager.cc
src/c++/perf_analyzer/thread_config.h

new CLI arg `--request-count`, which when specified tells PA exactly how many requests to issue for the experiment
Works with concurrency, request-rate, and custom load
Also:
- Combined thread_config classes into one, so that the base LoadWorker class has access to it
- Cleaned up some printing

Support for fixed number of requests

---

.github/workflows/python-package-genai.yml
src/c++/perf_analyzer/genai-perf/genai_perf/llm_metrics.py
src/c++/perf_analyzer/genai-perf/genai_perf/plots/base_plot.py
src/c++/perf_analyzer/genai-perf/genai_perf/plots/box_plot.py
src/c++/perf_analyzer/genai-perf/genai_perf/plots/heat_map.py
src/c++/perf_analyzer/genai-perf/genai_perf/plots/plot_config.py
src/c++/perf_analyzer/genai-perf/genai_perf/plots/plot_config_parser.py
src/c++/perf_analyzer/genai-perf/genai_perf/plots/plot_manager.py
src/c++/perf_analyzer/genai-perf/genai_perf/plots/scatter_plot.py
src/c++/perf_analyzer/genai-perf/genai_perf/utils.py
src/c++/perf_analyzer/genai-perf/genai_perf/wrapper.py
src/c++/perf_analyzer/genai-perf/tests/test_llm_metrics.py

GenAI-Perf [says it supports Python 3.8](https://github.com/triton-inference-server/client/blob/4ea63a50cbea2522180bbf84811f09e3bcc71d39/src/c%2B%2B/perf_analyzer/genai-perf/pyproject.toml#L40-L41). This pull request fixes the breaking Python 3.8 code (i.e. removes features only available in 3.9+). To confirm it continues to support Python 3.8, it adds a job to build and run testing against 3.8 for each PR.
A few retrofits for Python 3.8:
1. Using the typing library rather than the built-in subscriptable types.
2. Using Union rather than "|"
3. Using a custom pairwise function rather than the itertools function
4. Using custom logic rather than the in-built removeprefix function

Support Python 3.8 in GenAI-Perf

---

src/c++/perf_analyzer/genai-perf/genai_perf/parser.py
src/c++/perf_analyzer/genai-perf/tests/test_cli.py

Some model names include slash (`/`) in their model name (e.g. Huggingface). This will break artifacts directory creation, so preprocess the model name so that we do not have slash character in the model name.

Filter model name with slash for artifact path

---

src/c++/perf_analyzer/genai-perf/genai_perf/llm_metrics.py
src/c++/perf_analyzer/genai-perf/tests/test_llm_metrics.py

When preprocessing responses, if all responses are either empty or null, then the `res_outputs` and `res_timestamps` will eventually be empty and will raise index out of range error. Instead of indexing 0-th and last element, check if the list is empty or not.

Fix response preprocessing bug

---

src/c++/perf_analyzer/genai-perf/tests/test_cli.py

For capsys to check logged output, the logger needs to be initialized in each unit test. Right now, if the parser starts logging output, this test will still pass (unexpected behavior).
There is a separate ticket to look into creating a fixture so that this code can be run for every unit test from one place.

Initialize logger for unit tests

---

src/c++/perf_analyzer/inference_profiler.cc

This check is needed so that test_inference_profiler unit test doesn't fail.

Add a check if ModelParser pointer is nullptr

---

src/c++/perf_analyzer/infer_context.h
src/c++/perf_analyzer/test_request_rate_manager.cc

This fixes both concurrency and request rate issues around iterating through the input data set
As an example, in the case of 4 worker threads (for either request-rate or concurrency), the index of the input-data for the sent data would be:
- Before fix: 0,0,0,0,4,4,4,4,8,8,8,8
- After fix: 0,1,2,3,4,5,6,7,8,9,10,11
Also added some multi-worker test cases that failed before the fix, and now pass.

Fix request-rate request order

---

src/c++/perf_analyzer/genai-perf/genai_perf/main.py
src/c++/perf_analyzer/genai-perf/genai_perf/tokenizer.py

For those using GenAI-Perf's "--help" option, it takes 1-3 seconds to generate the help menu due to all of the heavy imports (especially the transformers library). This pull request defers those imports until they are needed. This should not impact normal runtime (see below), but it does speed up the "--help call" by up to 16x for the average case, 24x for the first-time call, and 47x for the non-parallelized case. See the runtime profiles below.
**"--help" option**
Before changes (1-3s):
After changes (62.3ms):
For completeness, the `-h` option:
**Full run**
Before changes (39.0s):
After changes (38.1s):
**Passing unit tests**

Speed up GenAi-Perf's help call

---

src/c++/perf_analyzer/genai-perf/genai_perf/main.py
src/c++/perf_analyzer/genai-perf/genai_perf/tokenizer.py

Reverts triton-inference-server/client#669. That pull request does not actually print the help message when "-h/--help" is called.

Revert "Speed up GenAi-Perf's help call"

---

src/c++/perf_analyzer/genai-perf/genai_perf/llm_metrics.py

vLLM does not include content in the first response from the server.
Now we filter for the content entry missing before preprocessing merged requests.

Patch vLLM for missing content entry

---

src/c++/library/http_client.cc
src/c++/library/http_client.h

Copying over the OpenAI HTTP client fix to general HTTP client. The client will now send all the requests in a timely fashion.
Changed to use multi_curl_poll and multi_curl_wakeup to allow for handling of new requests and ongoing requests.
1. Load generation thread adds requests into a mutex protected map.
2. Load generation thread calls multi_curl_wakeup
3. AsyncTransferThread adds new requests to multi_handle
4. AsyncTransferThread reads / writes to requests via curl_multi_perform
5. AsyncTransferThread processes complete requests via curl_multi_info_read
6. AsyncTransferThread waits for new data or new requests or exit signal using curl_multi_poll
7. When exiting, AsyncTransferThread removes and releases requests added to multi_handle
8. Note: Load generation thread only initializes …

Fix HTTP Client Async Code for Request Rate

---

src/c++/perf_analyzer/inference_profiler.cc
src/c++/perf_analyzer/inference_profiler.h
src/c++/perf_analyzer/perf_analyzer.cc
src/c++/perf_analyzer/test_inference_profiler.cc

After fixing the async request rate case, perf analyzer no longer stabilizes most of the time for smaller models due to the latency being more variable in the async case. As a result, only use throughput (inferences per second) for stabilizing. PA quite quickly with these updates.
Before changes:
DenseNet
After changes:
DenseNet

Stabilize PA on throughput only for async case

---

src/c++/perf_analyzer/data_loader.cc
src/c++/perf_analyzer/infer_context.cc
src/c++/perf_analyzer/tensor_data.h

We were seeing L0_long_running_stress test failing due to an output doesn't match to the expected output. 
```
Successfully read data for 1 stream/streams with 3 step/steps.
...
Inferences/Second vs. Client Average Batch Latency
Concurrency: 2, throughput: 3138.92 infer/sec, latency 600 usec
Thread [1] had error: Output doesn't match expected output
```
It seems like it's because the order of  `infer_data_.outputs_` and `infer_data_.expected_outputs_` might be different, so we need to make sure that we are comparing the correct validation output based on the same output name. Shout out to @rmccorm4 who quickly came up with the solution! This PR is based on https://github.com/triton-inference-server/client/pull/685

fix: Get validation outputs by name rather than index

---

src/c++/library/http_client.cc
src/c++/library/http_client.h
src/c++/perf_analyzer/client_backend/openai/http_client.cc
src/c++/perf_analyzer/client_backend/openai/http_client.h
src/c++/perf_analyzer/inference_profiler.cc
src/c++/perf_analyzer/inference_profiler.h
src/c++/perf_analyzer/perf_analyzer.cc
src/c++/perf_analyzer/test_inference_profiler.cc

Changed to use `multi_curl_poll` and `multi_curl_wakeup` to allow for handling of new requests and ongoing requests.
1) Load generation thread adds requests into a mutex protected map.
2) Load generation thread calls `multi_curl_wakeup`
3) AsyncTransferThread adds new requests to `multi_handle`
4) AsyncTransferThread reads / writes to requests via `curl_multi_perform`
5) AsyncTransferThread processes complete requests via `curl_multi_info_read`
6) AsyncTransferThread waits for new data or new requests or exit signal using `curl_multi_poll`
7) When exiting, AsyncTransferThread removes and releases requests added to `multi_handle`
Note: Load generation thread only initializes and calls `curl_multi_wakeup` on `multi_handle`, all other operations are done in the AsyncTransferThread
--
Similar …

fix: Fix Client Http Async Code for Request Rate

---

src/c++/perf_analyzer/genai-perf/README.md
src/c++/perf_analyzer/genai-perf/genai_perf/llm_inputs/llm_inputs.py
src/c++/perf_analyzer/genai-perf/genai_perf/parser.py
src/c++/perf_analyzer/genai-perf/tests/test_llm_inputs.py

Allow multiple prompts to be passed in via --input-file as a JSONL file. Each one should be on a separate JSON object (on a new line) with the field "text_input".

Allow multiple prompts to be supplied via --input-file to GenAI-Perf

---

src/c++/perf_analyzer/genai-perf/genai_perf/export_data/console_exporter.py
src/c++/perf_analyzer/genai-perf/tests/test_console_exporter.py

Remove ITL from console when non-streaming

---

src/c++/perf_analyzer/genai-perf/genai_perf/export_data/console_exporter.py
src/c++/perf_analyzer/genai-perf/genai_perf/export_data/csv_exporter.py
src/c++/perf_analyzer/genai-perf/genai_perf/export_data/exporter_config.py
src/c++/perf_analyzer/genai-perf/genai_perf/export_data/json_exporter.py
src/c++/perf_analyzer/genai-perf/genai_perf/export_data/output_reporter.py
src/c++/perf_analyzer/genai-perf/genai_perf/main.py
src/c++/perf_analyzer/genai-perf/genai_perf/metrics/__init__.py
src/c++/perf_analyzer/genai-perf/genai_perf/metrics/llm_metrics.py
src/c++/perf_analyzer/genai-perf/genai_perf/metrics/metrics.py
src/c++/perf_analyzer/genai-perf/genai_perf/metrics/statistics.py
src/c++/perf_analyzer/genai-perf/genai_perf/profile_data_parser/profile_data_parser.py
src/c++/perf_analyzer/genai-perf/tests/test_console_exporter.py
src/c++/perf_analyzer/genai-perf/tests/test_csv_exporter.py
src/c++/perf_analyzer/genai-perf/tests/test_json_exporter.py
src/c++/perf_analyzer/genai-perf/tests/test_llm_metrics.py
src/c++/perf_analyzer/genai-perf/tests/test_metrics.py
src/c++/perf_analyzer/genai-perf/tests/test_profile_data_parser.py

It looks like a lot of changes but really they're mostly just reduce/refactoring the exporters and fix/adding the unit tests.
Major changes
1. Introduce a small `MetricMetadata` dataclass to store metric name and unit information.
2. `Metrics` and `LLMMetrics` can now return list of request and system metrics.
3. Both `ConsoleExporter` and `CsvExporter` uses these request and system metrics separation to construct table or write to a file.
4. `ProfileDataParser` can now parse profile data and compute base metrics (e.g. request latency, request throughput).
5. Fix/Add tests
Console output:
```bash
Embedding Metrics
┏━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━┳━━━━━━━┳━━━━━━━┳━━━━━━━┳━━━━━━━┳━━━━━━━┓
┃            Statistic ┃   avg ┃   min ┃   max ┃   p99 ┃   p90 ┃   p75 ┃ …
```

Support embedding metrics and output export

---

src/c++/perf_analyzer/genai-perf/genai_perf/metrics/statistics.py

This PR updates the unit assignment for metrics in GenAI-Perf. It switches from if branching to if/elif/else to avoid overwrites with unexpected behavior. This should make no difference other than an efficiency in gain in the expected cases, but this will act as a stopgap to avoid unexpected behavior if a metric meets the criteria of multiple branches.
Long-term, we want to identify a consistent way to categorize metrics that makes it impossible for a metric to match the criteria of multiple branches.
Note: For ease, this PR will be rebased off of https://github.com/triton-inference-server/client/pull/715 once https://github.com/triton-inference-server/client/pull/719 is merged. It will not be merged until then. Rather than run CI for this small change, it will be easier to incorporate it …

Update GenAI-Perf metric unit assignment to avoid overwrites

---

src/c++/perf_analyzer/inference_profiler.cc
src/c++/perf_analyzer/inference_profiler.h
src/c++/perf_analyzer/test_inference_profiler.cc

When the request-count feature is used, the "measurement window" should be considered to be from the start of the first request to the final response of all requests.
Note that GenAI-Perf ignores windows and was already effectively doing this. There was a mismatch in what PA reported and what GAP reported. This PR fixes the PA reporting (which is important if the feature is used for standalone PA)
Before the fix, you can see that there were 20 requests in the 1-second window, so it claimed a throughput of 20/s. However, those all finished well before the 1 second was up, and the real throughput was more than double.
Before:
After:
This case where the whole test is less than 1 second is obviously an extreme case, but it helps highlight the problem.

Clamp window for request-count

---

src/c++/perf_analyzer/genai-perf/genai_perf/main.py
src/c++/perf_analyzer/genai-perf/genai_perf/parser.py
src/c++/perf_analyzer/genai-perf/tests/test_artifacts.py
src/c++/perf_analyzer/genai-perf/tests/test_cli.py

This pull request:
- Prevents the plots directory from being created when --generate-plots is not called
- Protects the embeddings/rankings endpoints from using the --generate-plots option until it is supported
- Adds testing for parser errors (--streaming/--generate-plots)
Rankings can no longer be called with --generate-plots:
Embeddings can no longer be called with --generate-plots:
Plots directory not created without --generate-plots:

Guard GenAI-Perf plot generation

---

src/c++/perf_analyzer/genai-perf/README.md
src/c++/perf_analyzer/genai-perf/docs/embeddings.md
src/c++/perf_analyzer/genai-perf/docs/lora.md
src/c++/perf_analyzer/genai-perf/docs/rankings.md
src/c++/perf_analyzer/genai-perf/genai_perf/llm_inputs/llm_inputs.py
src/c++/perf_analyzer/genai-perf/genai_perf/profile_data_parser/llm_profile_data_parser.py
src/c++/perf_analyzer/genai-perf/genai_perf/profile_data_parser/profile_data_parser.py
src/c++/perf_analyzer/genai-perf/tests/test_profile_data_parser.py

Support Hugging Face Text Embeddings Interface's re-ranker API. This extends the ranking endpoint-type to Hugging Face TEI. If a user specifies "--extra-inputs rankings:tei", then the Hugging Face TEI is used.
Main changes:
- Added documentation on how to run the ranking endpoint with [Hugging Face's re-ranker API](https://huggingface.co/docs/text-embeddings-inference/en/quick_tour#re-rankers))
- When rankings:tei is passed in as an extra inputs, GenAI-Perf logic routes to use the HuggingFace TEI re-ranker API instead for benchmarking ranking
- The profile data JSON file now checks for the HuggingFace TEI re-ranker endpoint (`reranker`)
- Added profile unit parsing unit tests for this endpoint
- Updated our documentation to avoid the use of gerunds in the extra tutorials, consistent with …

Add support for Hugging Face Text Embeddings Interface's re-ranker API

---

src/c++/perf_analyzer/genai-perf/genai_perf/profile_data_parser/llm_profile_data_parser.py

Context: https://github.com/triton-inference-server/client/pull/728/files#r1664451669
Rankings support is only for request-level metrics, so the conditional branch specifying its input text is unnecessary. This commit was not merged as part of the original PR.

Remove unnecessary OpenAI rankings parsing branch

---

src/c++/perf_analyzer/genai-perf/docs/rankings.md

Correct the name of Hugging Face TEI ([inference]((https://huggingface.co/docs/text-embeddings-inference/en/quick_tour#re-rankers), not interface).

Update the name of Hugging Face TEI

---

src/c++/perf_analyzer/docs/cli.md
src/c++/perf_analyzer/genai-perf/README.md

This pull request clarifies the documentation around some new args.
For perf analyzer, include request-count in documentation. For GenAI-Perf, update the --input-file description to show that multiple prompts can now be included.

Clarify new arguments in documentation

---

src/c++/perf_analyzer/genai-perf/README.md
src/c++/perf_analyzer/genai-perf/docs/embeddings.md
src/c++/perf_analyzer/genai-perf/docs/lora.md
src/c++/perf_analyzer/genai-perf/docs/rankings.md
src/c++/perf_analyzer/genai-perf/docs/tutorial.md
src/c++/perf_analyzer/genai-perf/genai_perf/parser.py
src/c++/perf_analyzer/genai-perf/genai_perf/test_end_to_end.py
src/c++/perf_analyzer/genai-perf/tests/test_cli.py
src/c++/perf_analyzer/genai-perf/tests/test_console_exporter.py
src/c++/perf_analyzer/genai-perf/tests/test_csv_exporter.py
src/c++/perf_analyzer/genai-perf/tests/test_json_exporter.py
src/c++/perf_analyzer/genai-perf/tests/test_wrapper.py

With compare being moved into a subcommand, there should be a profile subcommand for profiling with GenAI-Perf. Currently, those args just float so `genai-perf compare <args>` is used for compare but `genai-perf <args>` does not. This is inconsistent and can lead to special handling or errors with parsing.
With this change, `genai-perf <profile>` is the sole entryway for profiling models via GenAI-Perf. All documentation and tests are cleaned up as well.

Move GenAI-Perf profiling to its own subcommand

---

src/c++/perf_analyzer/genai-perf/genai_perf/llm_inputs/llm_inputs.py
src/c++/perf_analyzer/genai-perf/tests/test_llm_inputs.py

The PR allows users to provide a file that contains multi-modal data (in this case, texts and images) which will be used to generate input payloads for OpenAI Chat Completions. 
For instance, when the user provides a file with multi-modal data:
```
{ "text_input": "prompt1", "image": "<path>/<to>/<image1>"},
{ "text_input": "prompt2", "image": "<path>/<to>/<image2>"},
...
```
GenAI-Perf will create a multi-modal input payload as following:
```
{
"message": [
{
"role": "user",
"content": [
{
"type": "text",
"text": "prompt1",
},
{
"type": "image_url",
"image_url": {
"url": "data:image/png;base64,...",
}
},
]
}
],
"model": "some-model"
},
{
"message": [
{
"role": "user",
"content": [
{
"type": "text",
"text": "prompt2",
},
{
"type": "image_url",
"image_url": {
"url": …
```

Support multi-modal input from file for OpenAI Chat Completions

---

src/c++/perf_analyzer/genai-perf/genai_perf/llm_inputs/llm_inputs.py
src/c++/perf_analyzer/genai-perf/genai_perf/parser.py
src/c++/perf_analyzer/genai-perf/genai_perf/profile_data_parser/llm_profile_data_parser.py
src/c++/perf_analyzer/genai-perf/genai_perf/utils.py

When JSON parsing fails in GenAI-Perf, return the string that failed to be parsed (up to 200 characters). This will help with debugging when the string is not in the format JSON expects.
Before changes:
After changes:
Note: This would be more useful for shorter strings (e.g. invalid response formats).

When JSON parsing fails, return the failed string

---

src/c++/perf_analyzer/client_backend/openai/openai_client.cc
src/c++/perf_analyzer/client_backend/openai/openai_client.h

For HTTP streaming endpoints which do not explicitly send a `[DONE]` message, updated to treat the HTTP request completion as a final response. 
This is backwards compatible and doesn't effect endpoints that do explicitly send `[DONE]`.
This is one change needed for Triton Generate as well as some TGI interfaces / servers.
Checks are added to ensure only a single final response is sent.

feat: Treat HTTP request completion as final response

---

src/c++/perf_analyzer/genai-perf/genai_perf/llm_inputs/llm_inputs.py
src/c++/perf_analyzer/genai-perf/genai_perf/llm_inputs/synthetic_image_generator.py
src/c++/perf_analyzer/genai-perf/tests/test_synthetic_image_generator.py

The PR allows users to add multimodal data to the synthetic prompts.
Generated images:
* are filled with uniform noise,
* will have randomized shape (controlled with `mean_size` and `dimiensions_stddev` parameters),
* user can choose image format from PNG or JPEG for base64 encoding.

Synthetic image generator

---

src/c++/perf_analyzer/command_line_parser.cc
src/c++/perf_analyzer/constants.h
src/c++/perf_analyzer/test_command_line_parser.cc

Currently, max_threads in PA is by default set to 16 in async mode. While using genai-perf, concurrency value can be passed as a CLI argument. However, the max_threads used by PA is still 16 although concurrency is set to a higher value. This change sets max_threads to concurrency if concurrency > 16. If concurrency <= 16, max_threads is by default set to 16.

Update default behavior for max threads PA async mode

---

src/c++/perf_analyzer/genai-perf/genai_perf/llm_inputs/synthetic_image_generator.py
src/c++/perf_analyzer/genai-perf/genai_perf/parser.py
src/c++/perf_analyzer/genai-perf/tests/test_json_exporter.py
src/c++/perf_analyzer/genai-perf/tests/test_synthetic_image_generator.py

With this MR, no image format is selected by default.
If no specific format is selected, the format will be selected at random for each generated image.
That simulates the case, where model users uses images of different format during conversation.

Random image format in SyntheticImageGenerator

---

src/c++/perf_analyzer/genai-perf/genai_perf/llm_inputs/llm_inputs.py
src/c++/perf_analyzer/genai-perf/genai_perf/parser.py
src/c++/perf_analyzer/genai-perf/tests/test_cli.py

The changes were already approved in #700. This PR just serves to move the commit to a new dev branch `tensorrtllm_engine`.

Add tensorrtllm_engine service-kind

---

src/c++/perf_analyzer/genai-perf/genai_perf/llm_inputs/llm_inputs.py
src/c++/perf_analyzer/genai-perf/genai_perf/parser.py
src/c++/perf_analyzer/genai-perf/genai_perf/wrapper.py
src/c++/perf_analyzer/genai-perf/tests/test_cli.py
src/c++/perf_analyzer/genai-perf/tests/test_llm_inputs.py

Generates input json file for PA to directly send requests to tensorrtllm engine:
```
{
"data":[
{
"input_ids":{
"content":[
1243,
1881,
697
],
"shape":[
3
]
},
"input_lengths":[
3
],
"request_output_len":[
256
]
},
...
}
```

Support input payload generation for tensorrtllm engine

---

src/c++/perf_analyzer/genai-perf/genai_perf/llm_inputs/llm_inputs.py
src/c++/perf_analyzer/genai-perf/genai_perf/parser.py
src/c++/perf_analyzer/genai-perf/genai_perf/profile_data_parser/llm_profile_data_parser.py
src/c++/perf_analyzer/genai-perf/genai_perf/wrapper.py
src/c++/perf_analyzer/genai-perf/tests/test_cli.py
src/c++/perf_analyzer/genai-perf/tests/test_json_exporter.py
src/c++/perf_analyzer/genai-perf/tests/test_llm_inputs.py
src/c++/perf_analyzer/genai-perf/tests/test_llm_profile_data_parser.py

With this MR, genai-perf can add random number of images per request. The number of images is sampled uniformly from a range controlled by `--images-count-min` and `--images-count-max` CLI arguments.

variable number of images per prompt

---

src/c++/library/CMakeLists.txt

1. Disable target compilation for WIN32.
2. Removing non existing parameter `-Wno-unused-parameter`. 
.ref: https://gcc.gnu.org/onlinedocs/gcc/Option-Summary.html

Update CMake file configuraion

---

src/c++/perf_analyzer/genai-perf/README.md

**Goal:** Create a "ghost directory" to direct users from the old GenAI-Perf location to the new one.

Redirect GenAI-Perf to new repo

---

src/c++/library/CMakeLists.txt

The Triton C++ client libraries do not actually use symbols in the CUDA Runtime library (`libcudart.so`).
So there's no need to `target_link_libraries()` to `CUDA::cudart`.
All they needed was access to `#include <cuda_runtime_api.h>` (which was implicitly being included by doing `target_link_libraries()`).
So I removed the `target_link_libraries ()`s and added `target_include_directories()`s.

Remove unnecessary linking of CUDA Runtime library

---

src/java-api-bindings/scripts/install_dependencies_and_build.sh

This PR enables support for Ubuntu 24.04 by adding a new job to the CI workflow.

Enable support for Ubuntu 24.04

---

src/java-api-bindings/scripts/install_dependencies_and_build.sh

Preinstalled maven package in ubuntu 24.04 includes JRE 1.21 which no longer compatible with compiler options 1.7 which we rely on in: 
https://github.com/search?q=repo%3Abytedeco%2Fjavacpp-presets+1.7+language%3A%22Maven+POM%22+&type=code
Related to: https://github.com/triton-inference-server/server/pull/7808

Removing maven installation as it causes side package installation

---

src/python/library/requirements/requirements_http.txt

Partially fix `L0_https--base` by upgrading `geventhttpclient` version to support Python3.12 on Ubuntu 24.04.
"Try with incorrect key" tests are still failing because of changes in `geventhttpclient` newer version.
Check the [conventional commit type](https://github.com/angular/angular/blob/22b96b9/CONTRIBUTING.md#type)
box here and add the label to the github PR.
- CI Pipeline ID:
20604304
- closes GitHub issue: #xxx

fix: Partial fix for L0_https

---

src/c++/library/CMakeLists.txt
src/c++/library/cencode.cc
src/c++/library/cencode.h
src/c++/library/http_client.cc

I tested that it builds correctly and that PA can compile and run correctly with it.

Fix C/C++ libb64 ABI incompatibility bug

---

README.md

Adds documentation on the new ORCA header metric support being added to Triton Server.
- [Feature Request](https://github.com/triton-inference-server/server/issues/7865)
- [PR](https://github.com/triton-inference-server/server/pull/7839)

Add ORCA header metrics documentation to README
