triton-inference-server/client

src/c++/perf_analyzer/perf_utils.h

The bug was exposed by the recent format fixes.
https://gitlab-master.nvidia.com/dl/dgx/tritonserver/-/pipelines/2286187

Fixes the perf_analyzer build

---

src/c++/perf_analyzer/client_backend/tensorflow_serving/tfserve_grpc_client.cc
src/c++/perf_analyzer/perf_utils.cc

Hi, Just Fixed Bugs.
1. It should Add 4 bytes for copied_byte_size var in each  str.
2. correct spelling for Spelling mistakes

Fixed bugs for TFS backend

---

src/c++/examples/CMakeLists.txt
src/c++/examples/simple_grpc_keepalive_client.cc
src/c++/library/grpc_client.cc
src/c++/library/grpc_client.h
src/python/examples/simple_grpc_infer_client.py
src/python/examples/simple_grpc_keepalive_client.py
src/python/library/tritonclient/grpc/__init__.py

Expose GRPC KeepAlive parameters to triton client

---

src/python/library/tritonclient/grpc/__init__.py
src/python/library/tritonclient/http/__init__.py

This PR updates python tritonclient. Updating the examples require that L0_grpc and L0_http be changed as well as the C++ clients. This will be done in a subsequent PR.

Updated python clients to support string sequence IDs

---

src/c++/library/grpc_client.cc

Cherry-pick PR
* Create new GRPC channel to work around max connection concurrency
* Modify channel assignment to prefer share
* Address comment

Create new GRPC channel to work around max connection concurrency (#55)

---

src/java-api-bindings/scripts/install_dependencies_and_build.sh
src/java/README.md
src/java/pom.xml

Server side change: https://github.com/triton-inference-server/server/pull/4100

update java client build and remove old maven build artifacts

---

src/python/examples/image_client.py

C++ image_client.cc accounts for whether or not model supports batching when checking `FLAGS.batch_size` argument, but the python client did not.
This fixes https://github.com/triton-inference-server/server/issues/4310.

Account for model supporting batching in image client.py

---

README.md

Add section on custom ChannelArguments client examples

---

src/c++/perf_analyzer/inference_profiler.cc
src/c++/perf_analyzer/inference_profiler.h
src/c++/perf_analyzer/test_inference_profiler.cc

* Fix std dev integer overflow issue
* Addressed comments
* Fix comment
* Fix calculation
* Addressed comments

Fix std dev integer overflow issue (#125)

---

src/c++/perf_analyzer/client_backend/client_backend.cc
src/c++/perf_analyzer/client_backend/client_backend.h
src/c++/perf_analyzer/client_backend/triton/triton_client_backend.cc
src/c++/perf_analyzer/client_backend/triton/triton_client_backend.h
src/c++/perf_analyzer/perf_analyzer.cc

Related Server PR: https://github.com/triton-inference-server/server/pull/4684

Add Tracing to Perf Analyzer GRPC/HTTP Client

---

src/python/library/tritonclient/grpc/__init__.py
src/python/library/tritonclient/grpc/aio/__init__.py
src/python/library/tritonclient/http/__init__.py
src/python/library/tritonclient/http/aio/__init__.py

Rebase issues caused need for new branch.

Client modifications for new logging extension

---

src/c++/perf_analyzer/load_manager.h
src/c++/perf_analyzer/request_rate_manager.h
src/c++/perf_analyzer/test_request_rate_manager.cc

Unit tests for the following functions:
CheckHealth()
SwapTimeStamps()
GetAccumulatedClientStat()
CountCollectedRequests()
BatchSize()
ResetWorkers()

UnitTest Public functions in RequestRateManager

---

src/c++/tests/cc_client_test.cc
src/python/examples/simple_grpc_model_control.py
src/python/examples/simple_http_model_control.py

Server: https://github.com/triton-inference-server/server/pull/4948
Core: https://github.com/triton-inference-server/core/pull/124

Add testing for loading model with override config

---

src/java/pom.xml

Update jackson databind to resolve the following issues:
https://github.com/advisories/GHSA-jjjh-jjxp-wpff
https://github.com/advisories/GHSA-rgv9-q543-rqg4

update jackson-databind for pulse

---

src/c++/perf_analyzer/test_command_line_parser.cc

Tim, here is a quick review to add the latest tests I created to the CLI. You can carry it forward from here.

Add more CLI Unit tests

---

src/c++/perf_analyzer/CMakeLists.txt
src/c++/perf_analyzer/client_backend/mock_client_backend.h
src/c++/perf_analyzer/load_manager.cc
src/c++/perf_analyzer/test_load_manager.cc
src/c++/perf_analyzer/test_load_manager_base.h
src/c++/perf_analyzer/test_request_rate_manager.cc

moved testing of loadmanager functions into test_load_manager
moved testing code that is sharable between ConcurrencyManager and RequestRateManager into a new base class

Refactor unit test code

---

src/java/pom.xml

This version shouldn't contain CVE 
https://mvnrepository.com/artifact/com.fasterxml.jackson.core/jackson-databind

Update Java 'jackson-databind' dependency version

---

src/c++/perf_analyzer/client_backend/triton_c_api/shared_library.cc
src/c++/perf_analyzer/client_backend/triton_c_api/triton_c_api_backend.cc
src/c++/perf_analyzer/client_backend/triton_c_api/triton_loader.cc
src/c++/perf_analyzer/command_line_parser.cc
src/c++/perf_analyzer/command_line_parser.h
src/c++/perf_analyzer/perf_analyzer.cc
src/c++/perf_analyzer/test_command_line_parser.cc

* Replace instances of FAIL_IF_ERROR with `RETURN_IF_ERROR`
* Improve error messages
* Remove debug info

Clean up C-API error and info messages

---

src/c++/library/http_client.cc

* Fix syntax error on windows
* Switch fix to use NOMINMAX
* Switch fix to use undef min
* Add comment on why NOMINMAX did not work

Add https to windows curl (#192)

---

src/c++/perf_analyzer/concurrency_manager.cc

There was a race condition where the thread creation and configuration (in ReconfigThreads) was timed in such a way that the worker thread got stuck waiting to be told what its concurrency should be. This was possible if the concurrency was updated right at (after?) this line:
https://github.com/triton-inference-server/client/blob/main/src/c%2B%2B/perf_analyzer/concurrency_manager.cc#L343
In that case the condition still evaluates to false, and the condition variable is not woken up by the change.
The solution is to guard updates to the variable used in the condition_variable (concurrency_) behind the wake up mutex.

Fix deadlock in concurrency thread configuration

---

src/python/library/requirements/requirements_grpc.txt

cherry picking https://github.com/triton-inference-server/client/pull/201

update grpcio versions (#201)

---

src/c++/perf_analyzer/concurrency_manager.cc
src/c++/perf_analyzer/concurrency_manager.h
src/c++/perf_analyzer/concurrency_worker.cc
src/c++/perf_analyzer/concurrency_worker.h
src/c++/perf_analyzer/request_rate_manager.cc
src/c++/perf_analyzer/request_rate_manager.h
src/c++/perf_analyzer/request_rate_worker.cc
src/c++/perf_analyzer/request_rate_worker.h
src/c++/perf_analyzer/test_request_rate_manager.cc

Refactored the `infer` function of the workers to be significantly cleaner by extracting out functions.

first order refactor of workers

---

src/c++/perf_analyzer/CMakeLists.txt
src/c++/perf_analyzer/concurrency_manager.cc
src/c++/perf_analyzer/concurrency_manager.h
src/c++/perf_analyzer/concurrency_worker.h
src/c++/perf_analyzer/iworker.h
src/c++/perf_analyzer/load_worker.h
src/c++/perf_analyzer/request_rate_manager.cc
src/c++/perf_analyzer/request_rate_manager.h
src/c++/perf_analyzer/request_rate_worker.h
src/c++/perf_analyzer/test_request_rate_manager.cc

Create IWorker interface
Push a few more common variables into base class

Combine worker interfaces into one

---

src/c++/perf_analyzer/concurrency_worker.cc
src/c++/perf_analyzer/concurrency_worker.h
src/c++/perf_analyzer/load_worker.cc
src/c++/perf_analyzer/load_worker.h
src/c++/perf_analyzer/request_rate_worker.cc
src/c++/perf_analyzer/request_rate_worker.h

Refactor ConcurrencyWorker inference request code to match format of RequestRateWorker
Extract that code to send one request up to LoadWorker
Extract async callback code up to LoadWorker
Extract UpdateJson code up to LoadWorker

Extract common functionality from Workers to base class

---

src/c++/perf_analyzer/concurrency_worker.cc
src/c++/perf_analyzer/concurrency_worker.h
src/c++/perf_analyzer/load_worker.cc
src/c++/perf_analyzer/load_worker.h
src/c++/perf_analyzer/request_rate_worker.cc
src/c++/perf_analyzer/request_rate_worker.h

Extract out the following functions:
WaitForOngoingRequests()
SyncClientStats()
ResetFreeCtxIds()
GetCtxId()
GetSeqStatIndex()
CreateContext() -- this one was extracted from both children and pushed up to parent

Extract more functions

---

src/c++/perf_analyzer/client_backend/mock_client_backend.h
src/c++/perf_analyzer/concurrency_manager.cc
src/c++/perf_analyzer/concurrency_manager.h
src/c++/perf_analyzer/custom_load_manager.cc
src/c++/perf_analyzer/custom_load_manager.h
src/c++/perf_analyzer/load_manager.cc
src/c++/perf_analyzer/load_manager.h
src/c++/perf_analyzer/perf_analyzer.cc
src/c++/perf_analyzer/request_rate_manager.cc
src/c++/perf_analyzer/request_rate_manager.h
src/c++/perf_analyzer/test_concurrency_manager.cc
src/c++/perf_analyzer/test_load_manager.cc
src/c++/perf_analyzer/test_load_manager_base.h
src/c++/perf_analyzer/test_request_rate_manager.cc

Testing the shared memory methods are called for the various shared memory options.

add shared mem testing

---

src/grpc_generated/java/examples/pom.xml
src/grpc_generated/java/library/pom.xml

Update apache tomcat to latest version

upgrade tomcat version to tomcat 9

---

src/c++/perf_analyzer/client_backend/mock_client_backend.h
src/c++/perf_analyzer/test_concurrency_manager.cc
src/c++/perf_analyzer/test_load_manager_base.h
src/c++/perf_analyzer/test_request_rate_manager.cc

Add testing to request rate manager and concurrency manager for append raw and shared memory method calls.

Request rate manager shared memory infer input testing

---

src/python/examples/memory_growth_test.py
src/python/library/requirements/requirements_grpc.txt
src/python/library/tritonclient/grpc/__init__.py

Since 1.51.1 grpc does not fail client memory growth test, relax grpc requirements.

Relax GRPC requirements

---

src/python/library/tritonclient/grpc/__init__.py
src/python/library/tritonclient/grpc/aio/__init__.py
src/python/library/tritonclient/http/__init__.py
src/python/library/tritonclient/http/aio/__init__.py

Add parameters to HTTP/GRPC clients

---

src/python/library/tests/test_inference_server_client.py
src/python/library/tritonclient/http/__init__.py

Closes #260 
Update unit test to show correct error on a plain text response.

Non json http response testing

---

.gitignore
src/c++/perf_analyzer/client_backend/mock_client_backend.h
src/c++/perf_analyzer/command_line_parser.cc
src/c++/perf_analyzer/command_line_parser.h
src/c++/perf_analyzer/inference_profiler.cc
src/c++/perf_analyzer/inference_profiler.h
src/c++/perf_analyzer/mock_model_parser.h
src/c++/perf_analyzer/model_parser.cc
src/c++/perf_analyzer/model_parser.h
src/c++/perf_analyzer/perf_analyzer.cc
src/c++/perf_analyzer/test_command_line_parser.cc
src/c++/perf_analyzer/test_model_parser.cc

Support the case where one of the bls models is a sequence
New CLI option bls-composing-models
Also prints out all bls composing model stats

support bls

---

src/c++/perf_analyzer/docs/benchmarking.md
src/c++/perf_analyzer/docs/input_data.md
src/c++/perf_analyzer/docs/measurements_metrics.md

Update links to correctly link between docs

Fix doc link formatting

---

src/c++/perf_analyzer/docs/cli.md
src/c++/perf_analyzer/docs/input_data.md
src/c++/perf_analyzer/docs/measurements_metrics.md

* add communication protocols section back in (it was dropped)
* revert missing hyphen from cli.md links
* clean up miscellaneous things in cli.md
* add section for bls-composing-models option to cli.md

Clean up docs branch

---

src/c++/perf_analyzer/request_rate_manager.cc
src/c++/perf_analyzer/request_rate_manager.h
src/c++/perf_analyzer/test_request_rate_manager.cc

Update create worker schedules to distribute threads/sequences amongst the workers more evenly.

update create worker schedules

---

src/c++/perf_analyzer/command_line_parser.cc
src/c++/perf_analyzer/command_line_parser.h
src/c++/perf_analyzer/concurrency_worker.cc
src/c++/perf_analyzer/ctx_id_tracker_factory.h
src/c++/perf_analyzer/custom_load_manager.cc
src/c++/perf_analyzer/custom_load_manager.h
src/c++/perf_analyzer/docs/cli.md
src/c++/perf_analyzer/mock_request_rate_worker.h
src/c++/perf_analyzer/perf_analyzer.cc
src/c++/perf_analyzer/request_rate_manager.cc
src/c++/perf_analyzer/request_rate_manager.h
src/c++/perf_analyzer/request_rate_worker.cc
src/c++/perf_analyzer/request_rate_worker.h
src/c++/perf_analyzer/test_custom_load_manager.cc
src/c++/perf_analyzer/test_request_rate_manager.cc

Add new cli option for the new sequence request rate mode

Add cli option for sequence request rate mode

---

src/c++/perf_analyzer/client_backend/mock_client_backend.h
src/c++/perf_analyzer/test_request_rate_manager.cc

Add testing for how many requests can be inflight for a given sequence

max seq inflight testing

---

src/c++/perf_analyzer/custom_load_manager.cc
src/c++/perf_analyzer/test_custom_load_manager.cc
src/c++/perf_analyzer/test_load_manager_base.h
src/c++/perf_analyzer/test_request_rate_manager.cc

Add support for custom schedule combined with serial sequences mode.

custom schedule support for serial sequences

---

src/c++/perf_analyzer/CMakeLists.txt
src/c++/perf_analyzer/data_loader.cc
src/c++/perf_analyzer/test_dataloader.cc

With these new tests, dataloader.cc is 52% covered by unit tests.
There are follow-up stories to fix a few bugs and cover the main uncovered blocks.
Going into a side feature branch. All FIXMEs will be resolved before merging into main

Phase 1 of dataloader testing

---

src/c++/perf_analyzer/test_dataloader.cc

Add testing for dataloader generating random string and non-string data
up to 62% coverage of dataloader.cc

dataloader: non-zero random data and string data testing

---

src/c++/perf_analyzer/test_dataloader.cc

b64 datatype
fill misc holes in coverage

dataloader b64 testing

---

src/c++/perf_analyzer/client_backend/triton/triton_client_backend.cc
src/c++/perf_analyzer/command_line_parser.cc
src/c++/perf_analyzer/perf_analyzer_exception.h

Fix bug where exceptions had corrupted error messages
Improve error when unable to connect to metrics port
Update default metrics URL

Fix corrupted error messages

---

src/java-api-bindings/scripts/install_dependencies_and_build.sh

Javacpp-presets PR: https://github.com/bytedeco/javacpp-presets/pull/1361
Developer tools test: https://github.com/triton-inference-server/developer_tools/pull/20
Server README PR: https://github.com/triton-inference-server/server/pull/5883

Update Java API build script to include C-API Wrapper Java API

---

src/c++/library/http_client.cc
src/c++/perf_analyzer/CMakeLists.txt
src/c++/perf_analyzer/data_loader.cc
src/c++/perf_analyzer/data_loader.h
src/c++/perf_analyzer/mock_data_loader.h
src/c++/perf_analyzer/perf_utils.cc
src/c++/perf_analyzer/perf_utils.h
src/c++/perf_analyzer/test_dataloader.cc

Added a ton of testing, confirmed coverage of the dataloader file, and fixed a number of bugs.
Includes the fix for https://github.com/triton-inference-server/server/issues/5899

Dataloader testing and cleanup

---

src/python/library/tritonclient/grpc/aio/__init__.py

I have verified that it fixes the issue locally. I'm working on some testing that will be in a follow up PR.

Fix as_json for async client

---

src/c++/perf_analyzer/perf_utils.cc
src/c++/perf_analyzer/test_perf_utils.cc

- Add more unit tests for perf_utils

Add unit tests for util functions in PerfAnalyzer

---

src/java/src/main/java/triton/client/InferenceServerClient.java

Fixes https://github.com/triton-inference-server/server/issues/6066

fix off by one error

---

src/c++/perf_analyzer/command_line_parser.cc
src/c++/perf_analyzer/perf_utils.cc
src/c++/perf_analyzer/perf_utils.h
src/c++/perf_analyzer/test_command_line_parser.cc
src/c++/perf_analyzer/test_perf_utils.cc

This reverts commit c02ef4ea45a064d10975aa1bf32fc3315b443628.

Revert "Fix bugs and refine command line parsing (#377)"

---

src/python/library/tritonclient/grpc/_client.py
src/python/library/tritonclient/grpc/_infer_stream.py
src/python/library/tritonclient/grpc/_utils.py

Bringing in changes from the request cancellation branch.

Adding client-side request cancellation support

---

src/c++/perf_analyzer/test_command_line_parser.cc

Creates parity with changes from https://github.com/triton-inference-server/client/pull/410

Fix unit test failure

---

src/java-api-bindings/scripts/install_dependencies_and_build.sh

Cherry picks https://github.com/triton-inference-server/client/pull/409

change logic to true=1 in build script

---

README.md
src/python/library/requirements/requirements_cuda.txt
src/python/library/setup.py
src/python/library/tritonclient/utils/cuda_shared_memory/__init__.py

Extends from the PR #394  should resolve issue [#6246](https://github.com/triton-inference-server/server/issues/6246)

Make cuda-python optional package dependency

---

src/grpc_generated/go/README.rst
src/grpc_generated/go/go.mod
src/grpc_generated/go/go.sum
src/grpc_generated/java/examples/pom.xml
src/grpc_generated/java/library/pom.xml

Fix [BDSA-2023-2733](https://nspect.nvidia.com/vulnerability?id=BDSA-2023-2733) 
and [BDSA-2023-2732](https://nspect.nvidia.com/vulnerability?id=BDSA-2023-2732)

Fix HTTP/2 security issues and update README

---

src/c++/library/http_client.cc

Add request parameter passing for the http client

http request parameters

---

src/c++/perf_analyzer/CMakeLists.txt

* Add check for pa sha passed in via yaml + docker
* Update cmake execute command to change working dir
* Remove changes to top level Cmakelists files

fix pa sha (#445)

---

src/c++/perf_analyzer/docs/llm.md

@jbkyang-nvi made an excellent guide here: https://github.com/triton-inference-server/tutorials/blob/main/Popular_Models_Guide/Llama2/trtllm_guide.md
Leveraging it give users direction on using TRTLLM

trtllm instructions

---

src/python/library/tritonclient/grpc/aio/__init__.py

Fix gRPC AsyncIO import (#458)

---

src/python/library/tritonclient/grpc/_utils.py

Server: https://github.com/triton-inference-server/server/pull/6755
Core: https://github.com/triton-inference-server/core/pull/307
PYBE: https://github.com/triton-inference-server/python_backend/pull/333
Identity Backend: https://github.com/triton-inference-server/identity_backend/pull/28
Common: https://github.com/triton-inference-server/common/pull/111

Support Double-Type Inference Request/Response Parameters

---

src/grpc_generated/go/go.mod

Updating the GRPC Go package used in client to 1.62.0.

Updating GRPC GO package in client

---

src/c++/perf_analyzer/genai-pa/genai_pa/llm_inputs/llm_inputs.py
src/c++/perf_analyzer/genai-pa/tests/test_llm_inputs.py

Adds a new optional field called `dataset_name`. Replaced all relevant model_name usages and updated unit testing.

LlmInputs - Adding dataset_name to API

---

src/c++/perf_analyzer/genai-pa/genai_pa/main.py
src/c++/perf_analyzer/genai-pa/genai_pa/parser.py
src/c++/perf_analyzer/genai-pa/genai_pa/utils.py
src/c++/perf_analyzer/genai-pa/genai_pa/wrapper.py

Update the input module hookup to adhere to the new API

update input hookup

---

src/c++/perf_analyzer/genai-pa/genai_pa/llm_metrics.py
src/c++/perf_analyzer/genai-pa/tests/test_llm_metrics.py

- Add request throughput metric
- Add request latency metric
- Fix inter token latency calculation
- Small refactor
- Update test

Add request level metrics and fix ITL

---

src/c++/perf_analyzer/genai-pa/genai_pa/parser.py
src/c++/perf_analyzer/genai-pa/genai_pa/wrapper.py

Handle single letter args correctly
Add defaults to stability and window size

add sane defaults

---

src/c++/perf_analyzer/genai-perf/genai_perf/llm_metrics.py
src/c++/perf_analyzer/genai-perf/tests/test_llm_metrics.py

- Distinguish overall & per-request output token throughput
- Fix tests

Fix output token throughput

---

src/c++/perf_analyzer/genai-perf/genai_perf/llm_inputs/synthetic_prompt_generator.py

Workaround to avoid the tokenizer being created over and over (which was taking 45 seconds)

fix tokenizer

---

src/c++/perf_analyzer/genai-perf/genai_perf/llm_inputs/llm_inputs.py
src/c++/perf_analyzer/genai-perf/genai_perf/llm_inputs/synthetic_prompt_generator.py
src/c++/perf_analyzer/genai-perf/genai_perf/llm_metrics.py
src/c++/perf_analyzer/genai-perf/genai_perf/main.py
src/c++/perf_analyzer/genai-perf/genai_perf/parser.py
src/c++/perf_analyzer/genai-perf/genai_perf/tokenizer.py
src/c++/perf_analyzer/genai-perf/genai_perf/wrapper.py
src/c++/perf_analyzer/genai-perf/tests/test_llm_inputs.py
src/c++/perf_analyzer/genai-perf/tests/test_tokenizer.py

Putting this up for review, but it should not be merged until CI tests are up and we can verify this doesn't break anything.

Remove hardcoding of tokenizer and pass this in as an arg to LlmInputs

---

src/c++/perf_analyzer/genai-perf/README.md

Update GenAI-Perf main readme

---

src/c++/tests/cc_client_test.cc

Edit all Client tests which interact with Get Trace Settings and Update Trace Settings

Update client-side trace tests to check for newly returned trace mode

---

src/c++/tests/cc_client_test.cc

Tests passed in the local environment

Update client tests due to disabling dynamic trace file

---

src/c++/tests/cc_client_test.cc

Commit on main https://github.com/triton-inference-server/client/commit/85435d3698d9cbbb8526377d966a7d990207363b

Update client test due to disabling dynamic trace file (#579)

---

src/c++/perf_analyzer/genai-perf/genai_perf/llm_inputs/llm_inputs.py
src/c++/perf_analyzer/genai-perf/tests/test_llm_inputs.py

Update the legacy completions prompt to be a string rather than an array of strings.

Change openai prompt to string

---

src/c++/perf_analyzer/genai-perf/README.md
src/c++/perf_analyzer/genai-perf/docs/tutorial.md

Addresses more feedback from the VR

Continue to address readme VR feedback

---

src/c++/perf_analyzer/genai-perf/genai_perf/llm_inputs/llm_inputs.py
src/c++/perf_analyzer/genai-perf/genai_perf/llm_inputs/synthetic_prompt_generator.py
src/c++/perf_analyzer/genai-perf/tests/test_llm_inputs.py

Fixed synthetic prompt generation so that the number of tokens is correct
Fixed and tested synthetic prompt generation stddev and randomization
Tweaks to speed up unit tests.

Fix input token count

---

src/c++/perf_analyzer/genai-perf/README.md
src/c++/perf_analyzer/genai-perf/genai_perf/llm_inputs/llm_inputs.py
src/c++/perf_analyzer/genai-perf/genai_perf/parser.py
src/c++/perf_analyzer/genai-perf/genai_perf/test_end_to_end.py
src/c++/perf_analyzer/genai-perf/genai_perf/wrapper.py
src/c++/perf_analyzer/genai-perf/tests/test_cli.py
src/c++/perf_analyzer/genai-perf/tests/test_llm_inputs.py
src/c++/perf_analyzer/genai-perf/tests/test_llm_metrics.py
src/c++/perf_analyzer/genai-perf/tests/test_wrapper.py

trtllm is updated to tensorrtllm where appropiate in the codebase.

Update trtllm to tensorrtllm where appropriate

---

src/c++/perf_analyzer/genai-perf/README.md
src/c++/perf_analyzer/genai-perf/docs/tutorial.md

Update backend naming in docs: trtllm to tensortllm

---

src/python/library/tritonclient/http/_utils.py

This PR enhances performance by replacing the use of `struct.pack` with list operations. For more detailed numbers, please refer to the comments in Jira ticket DLIS-6498.
The improvement was observed in various scenarios:
**identity model(one input, one output)**
- Sending small tensor
Observed improvement of approximately **6.11%** in throughput 
- Sending larger tensor(1MB)
Observed improvement of approximately **2.26%** in throughput 
Considering that the number of inputs can impact performance, as it requires more work for both struct.pack and list operations.
**python model(three inputs, three outputs)**
- Sending larger tensor(1MB)
Observed improvement of approximately **6.71%** in throughput 
In addition to the experiments mentioned above, simply running the Python code without …

Optimize the request body creation in HTTP python clients

---

src/c++/perf_analyzer/genai-perf/genai_perf/llm_metrics.py

In vLLM outputs can be empty in the middle of the stream.

vLLM ITL fix

---

src/c++/library/http_client.cc

This adds the HTTP client timestamp back for the request end. In the previous change, it was removed. Now the HTTP times are correct.
Before changes (notice avg HTTP time is 0):
After changes:

Fix HTTP client REQUEST_END timestamp

---

src/c++/perf_analyzer/genai-perf/genai_perf/llm_metrics.py
src/c++/perf_analyzer/genai-perf/genai_perf/plots/plot_config_parser.py
src/c++/perf_analyzer/genai-perf/tests/test_llm_metrics.py

- Updated ITL calculation: ITL = (req latency - TTFT) / (OSL - 1)
- Updated unit tests
- Small refactor
CI Pipeline #: ~~15604638~~ 15629347 (new)

Update ITL calculation

---

src/c++/perf_analyzer/genai-perf/README.md

Add documentation on installing PA dependencies on Ubuntu
At least one approval is fine

Add documentation on installing PA dependencies on Ubuntu

---

src/c++/perf_analyzer/genai-perf/genai_perf/llm_inputs/llm_inputs.py
src/c++/perf_analyzer/genai-perf/genai_perf/parser.py
src/c++/perf_analyzer/genai-perf/tests/test_cli.py

Adding option and checks for tensorrtllm engine profiling.
Updates unit tests

Add tensorrtllm_engine option to service-kind and update testing

---

src/c++/perf_analyzer/genai-perf/genai_perf/llm_metrics.py
src/c++/perf_analyzer/genai-perf/tests/test_llm_metrics.py

Calculating total tokens from the sum of the chunks can result in numbers that are off (10% in the case of llama3).  This is due to the fact that our old WAR to use the "!" + text, actually results in a single token instead of 2 tokens somethings.  For example "!." is just 1 token instead of 2.  
```
!, [17581]                                                                                                                                                                                                                                                                       
!? [58490] …
```

Calculate total output token from full text

---

src/c++/perf_analyzer/genai-perf/docs/tutorial.md

Fix the tutorials and add links at the top

Fix tutorials

---

src/c++/perf_analyzer/genai-perf/tests/test_artifacts.py

This PR is a part of unit test epic for genai-perf and handles unit tests for artifacts produced by genai-perf.
https://jirasw.nvidia.com/browse/TPA-83
Folder structure
genai-perf
|__ genai-perf
|__ tests
|__ artifacts
|__ file1
|__ file 2
|__ plots
Artifacts are created inside genai-perf directory. Plots directory is created inside artifacts.
Ran the test with wrong path (used /genai_perf_artifact instead of /genai_perf_artifacts) to confirm the test fails.
When given the correct path, the test runs successfully.

Unit tests for artifacts produced by GenAI-Perf

---

src/c++/perf_analyzer/docs/input_data.md

https://github.com/triton-inference-server/client/pull/612/files#r1640384897

Update input data docs to include allowing outputs in provided directory

---

src/c++/perf_analyzer/genai-perf/genai_perf/llm_inputs/llm_inputs.py
src/c++/perf_analyzer/genai-perf/genai_perf/main.py
src/c++/perf_analyzer/genai-perf/genai_perf/parser.py
src/c++/perf_analyzer/genai-perf/tests/test_cli.py
src/c++/perf_analyzer/genai-perf/tests/test_llm_inputs_rankings.py

Add support for the NIM rankings API. 
The `--input-file` command is updated to take a directory or file. Directory is only support for rankings currently.
The user should pass a directory using `--input-file`. In that directory, must be 2 JSONL files named `queries.jsonl` and `passages.jsonl`. Genai-Perf will parse those files to generate stimulus payloads. 
Sample queries.jsonl:
```
{"text": "What sport does America's first openly gay, actively playing, professional team sport athlete play?"}
{"text": "What production company co-owned by Kevin Loader and Rodger Michell produced My Cousin Rachel?"}
{"text": "Who served as the 1st Vice President of Colombia under El Libertador?"}
```
Sample passages.jsonl:
```
{"text": "Eric Anderson (sociologist) Eric Anderson (born January 18, 1968) is …
```

Add rankings support

---

src/c++/perf_analyzer/genai-perf/genai_perf/main.py

Guard against accessing file path when input file option is None

Fix filepath 

---

src/c++/perf_analyzer/genai-perf/README.md

Link to the updated README in the branch: https://github.com/triton-inference-server/client/tree/hwoo-main-readme/src/c%2B%2B/perf_analyzer/genai-perf

Update GenAI-Perf README.md

---

README.md

Docs for GRPC Error codes (#775)

---

src/python/library/requirements/requirements_grpc.txt

Fixes https://github.com/triton-inference-server/client/issues/787

build: Bump tritonclient deps to grpcio>=1.63.0 and protobuf>=5.26.1,<6

---

src/grpc_generated/java/examples/pom.xml
src/grpc_generated/java/library/pom.xml

Default branch needst to be updated after 25.09 to include inroduced updates.

TPRD-1710: Update default branches post-25.09
